### ISSUE TITLE
Null Pointer Exception on Runnin CIFAR-10 example

### ISSUE THREAD

**Issue by rahulbhalerao001** [yahoo/CaffeOnSpark#10]
Hello,

I was able to run the MNIST example on AWS cluster following steps in the README. I then tried to run the Cifar-10 example following the steps
1. Downloading the data in lmdb format and mean image to master and both slaves
2. Modifying the data layer to MemoryData layer. as shown in attached files  
[cifar10_quick_solver.prototxt.txt](https://github.com/yahoo/CaffeOnSpark/files/149657/cifar10_quick_solver.prototxt.txt)
[cifar10_quick_train_test.prototxt.txt](https://github.com/yahoo/CaffeOnSpark/files/149658/cifar10_quick_train_test.prototxt.txt)

I am getting the below exceptions
`16/02/28 00:11:58 WARN TransportChannelHandler: Exception in connection from ip-172-31-29-90.eu-west-1.compute.internal/172.31.29.90:46325
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:384)
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:313)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:242)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
        at java.lang.Thread.run(Thread.java:745)
16/02/28 00:11:58 ERROR TaskSchedulerImpl: Lost executor 0 on ip-172-31-29-90.eu-west-1.compute.internal: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
`
AND

`16/02/28 00:12:00 WARN TaskSetManager: Lost task 1.1 in stage 1.0 (TID 5, ip-172-31-29-90.eu-west-1.compute.internal): java.lang.NullPointerException
        at com.yahoo.ml.caffe.CaffeOnSpark$$anonfun$train$1.apply$mcVI$sp(CaffeOnSpark.scala:158)
        at com.yahoo.ml.caffe.CaffeOnSpark$$anonfun$train$1.apply(CaffeOnSpark.scala:154)
        at com.yahoo.ml.caffe.CaffeOnSpark$$anonfun$train$1.apply(CaffeOnSpark.scala:154)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:103)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:47)
        at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)
        at scala.collection.AbstractIterator.to(Iterator.scala:1157)
        at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:265)
        at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1157)
        at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:252)
        at scala.collection.AbstractIterator.toArray(Iterator.scala:1157)
        at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$12.apply(RDD.scala:927)
        at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$12.apply(RDD.scala:927)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)`

It will be great if you could guide in solving it.

**Comment by junshi15** [comment]
Can you share your "spark-submit" command? I am wondering if it is due to the mean.binaryproto file.

**Comment by rahulbhalerao001** [comment]
Thank you for your reply. 

Here is it. 

`spark-submit --master spark://$(hostname):7077 \
    --files cifar10_quick_train_test.prototxt,cifar10_quick_solver.prototxt,mean.binaryproto \
    --conf spark.cores.max=${TOTAL_CORES} \
    --conf spark.driver.extraLibraryPath="${LD_LIBRARY_PATH}" \
    --conf spark.executorEnv.LD_LIBRARY_PATH="${LD_LIBRARY_PATH}" \
    --class com.yahoo.ml.caffe.CaffeOnSpark  \
    ${CAFFE_ON_SPARK}/caffe-grid/target/caffe-grid-0.1-SNAPSHOT-jar-with-dependencies.jar \
        -train \
        -features accuracy,loss -label label \
        -conf cifar10_quick_solver.prototxt \
    -clusterSize ${SPARK_WORKER_INSTANCES} \
        -devices ${DEVICES} \
    -connection ethernet \
        -model /cifar10.model \
    -output /cifar10_features_result`

**Comment by anfeng** [comment]
Please take the following steps, where step (2) will set up datasets on slave nodes.

(1) On master node, create LMDBs at file:///root/CaffeOnSpark/data/cifar10_train_lmdb/ and  file:///root/CaffeOnSpark/data/cifar10_test_lmdb/

(2) Execute ~/spark-ec2/copy-dir to make all nodes have identical data 
   ~/spark-ec2/copy-dir /root/CaffeOnSpark/data

(3) At master's /root/CaffeOnSpark/data folder, execute your spark-submit command.

**Comment by rahulbhalerao001** [comment]
@anfeng : As noted above I have manually copied the data folder from master to all the slaves, and am running the command from master's data folder.

**Comment by rahulbhalerao001** [comment]
Here is the directory structure of my machines.
______________________________________________________________________
Master
______________________________________________________________________
root@ip-172-31-25-116:~/CaffeOnSpark/data# ls mean.binaryproto cifar10_test_lmdb cifar10_train_lmdb/ cifar10_quick_solver.prototxt cifar10_quick_train_test.prototxt
cifar10_quick_solver.prototxt  cifar10_quick_train_test.prototxt  mean.binaryproto

cifar10_test_lmdb:
data.mdb  lock.mdb

cifar10_train_lmdb/:
data.mdb  lock.mdb
______________________________________________________________________
Slave1
______________________________________________________________________
root@ip-172-31-29-89:~/CaffeOnSpark/data# ls mean.binaryproto cifar10_test_lmdb cifar10_train_lmdb/ cifar10_quick_solver.prototxt cifar10_quick_train_test.prototxt
cifar10_quick_solver.prototxt      mean.binaryproto
cifar10_quick_train_test.prototxt

cifar10_test_lmdb:
data.mdb  lock.mdb

cifar10_train_lmdb/:
data.mdb  lock.mdb

______________________________________________________________________
Slave2
_________________________________________________________________
root@ip-172-31-29-90:~/CaffeOnSpark/data# ls mean.binaryproto cifar10_test_lmdb cifar10_train_lmdb/ cifar10_quick_solver.prototxt cifar10_quick_train_test.prototxt
cifar10_quick_solver.prototxt      mean.binaryproto
cifar10_quick_train_test.prototxt

cifar10_test_lmdb:
data.mdb  lock.mdb

cifar10_train_lmdb/:
data.mdb  lock.mdb

**Comment by mriduljain** [comment]
Could you print the size of these data files?

**Comment by rahulbhalerao001** [comment]
root@ip-172-31-25-116:~/CaffeOnSpark/data#  ls -l mean.binaryproto cifar10_test_lmdb cifar10_train_lmdb/ cifar10_quick_solver.prototxt cifar10_quick_train_test.prototxt
-rwxr-xr-x 1 root root   847 Feb 27 23:14 cifar10_quick_solver.prototxt
-rw-r--r-- 1 root root  3368 Feb 27 23:18 cifar10_quick_train_test.prototxt
-rw-r--r-- 1 root root 12299 Feb 27 21:51 mean.binaryproto

cifar10_test_lmdb:
total 40260
-rw-r--r-- 1 root root 41218048 Feb 27 21:33 data.mdb
-rw-r--r-- 1 root root     8192 Feb 27 21:33 lock.mdb

cifar10_train_lmdb/:
total 201212
-rw-r--r-- 1 root root 206032896 Feb 27 21:34 data.mdb
-rw-r--r-- 1 root root      8192 Feb 28 00:11 lock.mdb
______________________________________________________
root@ip-172-31-29-89:~/CaffeOnSpark/data# ls -l mean.binaryproto cifar10_test_lmdb cifar10_train_lmdb/ cifar10_quick_solver.prototxt cifar10_quick_train_test.prototxt
-rwxr-xr-x 1 root root   847 Feb 27 23:38 cifar10_quick_solver.prototxt
-rw-r--r-- 1 root root  3368 Feb 27 23:38 cifar10_quick_train_test.prototxt
-rw-r--r-- 1 root root 12299 Feb 27 23:38 mean.binaryproto

cifar10_test_lmdb:
total 40260
-rw-r--r-- 1 root root 41218048 Feb 27 23:38 data.mdb
-rw-r--r-- 1 root root     8192 Feb 27 23:38 lock.mdb

cifar10_train_lmdb/:
total 201216
-rw-r--r-- 1 root root 206032896 Feb 27 23:38 data.mdb
-rw-r--r-- 1 root root      8192 Feb 27 23:38 lock.mdb
____________________________________________________________
root@ip-172-31-29-90:~/CaffeOnSpark/data# ls -l mean.binaryproto cifar10_test_lmdb cifar10_train_lmdb/ cifar10_quick_solver.prototxt cifar10_quick_train_test.prototxt
-rwxr-xr-x 1 root root   847 Feb 27 23:39 cifar10_quick_solver.prototxt
-rw-r--r-- 1 root root  3368 Feb 27 23:39 cifar10_quick_train_test.prototxt
-rw-r--r-- 1 root root 12299 Feb 27 23:39 mean.binaryproto

cifar10_test_lmdb:
total 40260
-rw-r--r-- 1 root root 41218048 Feb 27 23:39 data.mdb
-rw-r--r-- 1 root root     8192 Feb 27 23:39 lock.mdb

cifar10_train_lmdb/:
total 201212
-rw-r--r-- 1 root root 206032896 Feb 27 23:39 data.mdb
-rw-r--r-- 1 root root      8192 Feb 27 23:39 lock.mdb

**Comment by anfeng** [comment]
Please change your net prototxt as below (removing "file://")
       mean_file: "file:///root/CaffeOnSpark/data/mean.binaryproto"
==> mean_file: "/root/CaffeOnSpark/data/mean.binaryproto"

**Comment by rahulbhalerao001** [comment]
Ok, thank you for the suggestion. I will try it out and let you know.
I had copied the format from lenet_memory_train_test.prototxt where it was
`file:///root/CaffeOnSpark/data/mnist_test_lmdb/`

**Comment by anfeng** [comment]
file:// or hdfs:// should be used by "source" only, not "mean_file".

**Comment by rahulbhalerao001** [comment]
Thank you for the help.

I am getting another set of excpetions now

`
*** Check failure stack trace: ***
F0228 05:08:53.482925  5587 data_transformer.cpp:239] Check failed: channels == img_channels (3 vs. 1) 
`
`
java.lang.NullPointerException
	at com.yahoo.ml.caffe.CaffeOnSpark$$anonfun$7.apply(CaffeOnSpark.scala:198)
	at com.yahoo.ml.caffe.CaffeOnSpark$$anonfun$7.apply(CaffeOnSpark.scala:194)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by junshi15** [comment]
It was complaining here:
https://github.com/yahoo/caffe/blob/4b677c6bf176bbe64ed642bc3f38b998ad6acd30/src/caffe/data_transformer.cpp#L239

By any chance you have black-and-white images in the dataset?

**Comment by rahulbhalerao001** [comment]
This is the out of the box CIFAR-10 data set.
The mean image also has been produced  from the Caffe script.
So I highly doubt that there will be black and white images in the dataset if the Cifar-10 data set does not have them.

**Comment by anfeng** [comment]
@rahulbhalerao001 I may have reproduced the problem. The root cause is at loading some image, since we got "WARN caffe.LMDB: Skipped image 00114". Do you see that WARN message?

16/02/28 16:59:36 WARN caffe.LMDB: Skipped image 00114
F0228 16:59:36.638281 27612 data_transformer.cpp:239] Check failed: channels == img_channels (3 vs. 1) 
*** Check failure stack trace: ***
F0228 16:59:36.638628 27610 data_transformer.cpp:239] Check failed: channels == img_channels (3 vs. 1) 
*** Check failure stack trace: ***

**Comment by anfeng** [comment]
The root cause is in our LMDB code that didn't keep the channels/height/width of LMDB entries. I have created a separated issue #12 for us to work on.

**Comment by rahulbhalerao001** [comment]
I am sorry for a delayed response.

I do not see any Skipped image warning though I do see channels == img_channels error.

Attaching the logs from the script and from spark UI in case I am missing anything.

[Exec1.txt](https://github.com/yahoo/CaffeOnSpark/files/150301/Exec1.txt)
[Exec2.txt](https://github.com/yahoo/CaffeOnSpark/files/150303/Exec2.txt)
[Exec3.txt](https://github.com/yahoo/CaffeOnSpark/files/150304/Exec3.txt)
[Exec4.txt](https://github.com/yahoo/CaffeOnSpark/files/150305/Exec4.txt)

[SparkSubmitLog.txt](https://github.com/yahoo/CaffeOnSpark/files/150302/SparkSubmitLog.txt)

**Comment by rahulbhalerao001** [comment]
@anfeng  : Do you think I am getting error due to #12, even though I do not see the WARN skip message, or do you think there is something I am missing?

**Comment by anfeng** [comment]
@rahulbhalerao001 I am quite certain that #12 causes this issue. We should have a PR on the change soon.

**Comment by rahulbhalerao001** [comment]
Thank you for your responses and support.

**Comment by anfeng** [comment]
This issue has been addressed with our latest code. Please verify it per steps at [GetStarted_EC2](https://github.com/yahoo/CaffeOnSpark/wiki/GetStarted_EC2) or [GetStarted_YARN](https://github.com/yahoo/CaffeOnSpark/wiki/GetStarted_yarn).
