### ISSUE TITLE
run CaffeOnSpark  standalone cluster,when run  "make build " something error

### ISSUE THREAD

**Issue by n080509** [yahoo/CaffeOnSpark#124]
run CaffeOnSpark  standalone cluster,when run  "make build " something error
as follow ,pls help me,thx

slave@128:~/CaffeOnSpark$ make build
cd caffe-public; make proto; make -j4 -e distribute; cd ..
make[1]: Entering directory `/home/slave/CaffeOnSpark/caffe-public'
make[1]: Nothing to be done for`proto'.
make[1]: Leaving directory `/home/slave/CaffeOnSpark/caffe-public'
make[1]: Entering directory`/home/slave/CaffeOnSpark/caffe-public'
# add proto

cp -r src/caffe/proto distribute/
# add include

cp -r include distribute/
mkdir -p distribute/include/caffe/proto
cp .build_release/src/caffe/proto/caffe.pb.h distribute/include/caffe/proto
# add tool and example binaries

cp .build_release/tools/compute_image_mean.bin .build_release/tools/finetune_net.bin .build_release/tools/test_net.bin .build_release/tools/convert_imageset.bin .build_release/tools/extract_features.bin .build_release/tools/train_net.bin .build_release/tools/device_query.bin .build_release/tools/upgrade_net_proto_text.bin .build_release/tools/upgrade_net_proto_binary.bin .build_release/tools/upgrade_solver_proto_text.bin .build_release/tools/net_speed_benchmark.bin .build_release/tools/caffe.bin distribute/bin
cp .build_release/examples/mnist/convert_mnist_data.bin .build_release/examples/cifar10/convert_cifar_data.bin .build_release/examples/cpp_classification/classification.bin .build_release/examples/siamese/convert_mnist_siamese_data.bin distribute/bin
# add libraries

cp .build_release/lib/libcaffe.a distribute/lib
install -m 644 .build_release/lib/libcaffe.so.1.0.0-rc3 distribute/lib
cd distribute/lib; rm -f libcaffe.so;   ln -s libcaffe.so.1.0.0-rc3 libcaffe.so
# add python - it's not the standard way, indeed...

cp -r python distribute/python
make[1]: Leaving directory `/home/slave/CaffeOnSpark/caffe-public'
export LD_LIBRARY_PATH="/home/y/lib64:/home/y/lib64/mkl/intel64:/home/slave/CaffeOnSpark/caffe-public/distribute/lib:/home/slave/CaffeOnSpark/caffe-distri/distribute/lib:/usr/lib64:/lib64 "; mvn -B package
[INFO] Scanning for projects...
[INFO] Reactor build order:
[INFO]   caffe
[INFO]   Unnamed - com.yahoo.ml:caffe-distri:jar:0.1-SNAPSHOT
[INFO]   Unnamed - com.yahoo.ml:caffe-grid:jar:0.1-SNAPSHOT
Downloading: http://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-ssh-external/2.6/wagon-ssh-external-2.6.pom
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] java.lang.NullPointerException
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.RuntimeException: java.lang.NullPointerException
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1455)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
        at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:2979)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:489)
        at org.apache.maven.wagon.providers.http.LightweightHttpWagon.fillInputData(LightweightHttpWagon.java:115)
        at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:116)
        at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
        at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
        at org.apache.maven.artifact.manager.DefaultWagonManager.getRemoteFile(DefaultWagonManager.java:546)
        at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifact(DefaultWagonManager.java:427)
        at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifact(DefaultWagonManager.java:382)
        at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:216)
        at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:90)
        at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepository(DefaultMavenProjectBuilder.java:558)
        at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromRepository(DefaultMavenProjectBuilder.java:251)
        at org.apache.maven.project.artifact.MavenMetadataSource.retrieveRelocatedProject(MavenMetadataSource.java:163)
        at org.apache.maven.project.artifact.MavenMetadataSource.retrieve(MavenMetadataSource.java:299)
        at org.apache.maven.extension.DefaultExtensionManager.addExtension(DefaultExtensionManager.java:115)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.findExtensions(DefaultLifecycleExecutor.java:196)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:178)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
        at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: java.lang.NullPointerException
        at com.sun.security.ntlm.Client.type3(Client.java:161)
        at sun.net.www.protocol.http.ntlm.NTLMAuthentication.buildType3Msg(NTLMAuthentication.java:241)
        at sun.net.www.protocol.http.ntlm.NTLMAuthentication.setHeaders(NTLMAuthentication.java:216)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1607)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        ... 28 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1 second
[INFO] Finished at: Tue Jul 26 08:02:42 EDT 2016
[INFO] Final Memory: 10M/723M
[INFO] ------------------------------------------------------------------------
make: **\* [build] Error 1
slave@128:~/CaffeOnSpark$

**Comment by junshi15** [comment]
It seems there was an issue with your maven settings.

**Comment by arundasan91** [comment]
Hi, 
You could try `sudo apt-get install maven` and redo the build again. To clean the build, use `make clean` inside the build directory. I had similar issues while building.
Thanks,
Arun

**Comment by mriduljain** [comment]
old bug. no update. Closing this. reopen if required
