### ISSUE TITLE
run CaffeOnSpark  standalone cluster,ERROR scheduler.TaskSchedulerImpl: Lost executor 2 on 10.136.159.133: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.

### ISSUE THREAD

**Issue by n080509** [yahoo/CaffeOnSpark#130]
when i run CaffeOnSpark,
because the gnome GUI i can't ,so i didn't open the master UI
i run the follow command on the master,and something error :
16/08/02 02:48:58 ERROR scheduler.TaskSchedulerImpl: Lost executor 2 on 10.136.159.133: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
16/08/02 02:48:58 WARN scheduler.TaskSetManager: Lost task 3.0 in stage 1.0 (TID 7, 10.136.159.133): ExecutorLostFailure (executor 2 exited caused by one of the running tasks) Reason: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.

16/08/02 02:48:58 ERROR scheduler.TaskSchedulerImpl: Lost executor 1 on 10.136.159.133: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
16/08/02 02:48:58 WARN scheduler.TaskSetManager: Lost task 1.0 in stage 1.0 (TID 5, 10.136.159.133): ExecutorLostFailure (executor 1 exited caused by one of the running tasks) Reason: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
16/08/02 02:49:06 ERROR scheduler.TaskSchedulerImpl: Lost executor 3 on 10.136.159.133: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
16/08/02 02:49:06 WARN scheduler.TaskSetManager: Lost task 2.0 in stage 1.0 (TID 6, 10.136.159.133): ExecutorLostFailure (executor 3 exited caused by one of the running tasks) Reason: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.

16/08/02 02:49:06 ERROR scheduler.TaskSchedulerImpl: Lost executor 0 on 10.136.159.133: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
16/08/02 02:49:06 WARN scheduler.TaskSetManager: Lost task 0.0 in stage 1.0 (TID 4, 10.136.159.133): ExecutorLostFailure (executor 0 exited caused by one of the running tasks) Reason: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
===command on the master===
export MASTER_URL=spark://$(hostname):7077
export SPARK_WORKER_INSTANCES=4
export CORES_PER_WORKER=6 
export TOTAL_CORES=$((${CORES_PER_WORKER}*${SPARK_WORKER_INSTANCES})) 
${SPARK_HOME}/sbin/start-slave.sh -c $CORES_PER_WORKER -m 3G ${MASTER_URL}
pushd ${CAFFE_ON_SPARK}/data
rm -rf ${CAFFE_ON_SPARK}/mnist_lenet.model
rm -rf ${CAFFE_ON_SPARK}/lenet_features_result
spark-submit --master ${MASTER_URL} \
    --files ${CAFFE_ON_SPARK}/data/lenet_memory_solver.prototxt,${CAFFE_ON_SPARK}/data/lenet_memory_train_test.prototxt \
    --conf spark.cores.max=${TOTAL_CORES} \
    --conf spark.task.cpus=${CORES_PER_WORKER} \
    --conf spark.driver.extraLibraryPath="${LD_LIBRARY_PATH}" \
    --conf spark.executorEnv.LD_LIBRARY_PATH="${LD_LIBRARY_PATH}" \
    --class com.yahoo.ml.caffe.CaffeOnSpark  \
    ${CAFFE_ON_SPARK}/caffe-grid/target/caffe-grid-0.1-SNAPSHOT-jar-with-dependencies.jar \
        -train \
        -features accuracy,loss -label label \
        -conf lenet_memory_solver.prototxt \
    -clusterSize ${SPARK_WORKER_INSTANCES} \
        -devices 1 \
    -connection ethernet \
        -model file:${CAFFE_ON_SPARK}/mnist_lenet.model \
        -output file:${CAFFE_ON_SPARK}/lenet_features_result

**Comment by n080509** [comment]
on slave ,i run the "[root@Slave1 spark-1.6.0-bin-hadoop2.6]# ./sbin/start-slave.sh 10.136.159.133:8080"
and  on master i run the caffeonspark command
the inform on the slave as follow:
[root@Slave1 spark-1.6.0-bin-hadoop2.6]# ./sbin/start-slave.sh 10.136.159.133:8080
starting org.apache.spark.deploy.worker.Worker, logging to /usr/local/spark-1.6.0-bin-hadoop2.6/logs/spark-root-org.apache.spark.deploy.worker.Worker-1-Slave1.out
[root@Slave1 spark-1.6.0-bin-hadoop2.6]# cat spark-root-org.apache.spark.deploy.worker.Worker-1-Slave1.out
cat: spark-root-org.apache.spark.deploy.worker.Worker-1-Slave1.out: ?2???‰é?￡??a?–??????–??????
[root@Slave1 spark-1.6.0-bin-hadoop2.6]# cd logs
[root@Slave1 logs]# cat spark-root-org.apache.spark.deploy.worker.Worker-1-Slave1.out
Spark Command: /usr/java/jdk1.7.0_15/bin/java -cp /usr/local/spark-1.6.0-bin-hadoop2.6/conf/:/usr/local/spark-1.6.0-bin-hadoop2.6/lib/spark-assembly-1.6.0-hadoop2.6.0.jar:/usr/local/spark-1.6.0-bin-hadoop2.6/lib/datanucleus-api-jdo-3.2.6.jar:/usr/local/spark-1.6.0-bin-hadoop2.6/lib/datanucleus-rdbms-3.2.9.jar:/usr/local/spark-1.6.0-bin-hadoop2.6/lib/datanucleus-core-3.2.10.jar -Xms1g -Xmx1g -XX:MaxPermSize=256m org.apache.spark.deploy.worker.Worker --webui-port 8081 10.136.159.133:8080
========================================
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
16/08/02 19:19:29 INFO Worker: Registered signal handlers for [TERM, HUP, INT]
16/08/02 19:19:29 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/08/02 19:19:29 INFO SecurityManager: Changing view acls to: root
16/08/02 19:19:29 INFO SecurityManager: Changing modify acls to: root
16/08/02 19:19:29 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(root); users with modify permissions: Set(root)
16/08/02 19:19:30 INFO Utils: Successfully started service 'sparkWorker' on port 49963.
16/08/02 19:19:30 INFO Worker: Starting Spark worker 192.168.1.134:49963 with 48 cores, 187.4 GB RAM
16/08/02 19:19:30 INFO Worker: Running Spark version 1.6.0
16/08/02 19:19:30 INFO Worker: Spark home: /usr/local/spark-1.6.0-bin-hadoop2.6
16/08/02 19:19:30 INFO Utils: Successfully started service 'WorkerUI' on port 8081.
16/08/02 19:19:30 INFO WorkerWebUI: Started WorkerWebUI at http://192.168.1.134:8081
16/08/02 19:19:30 INFO Worker: Connecting to master 10.136.159.133:8080...
16/08/02 19:19:30 ERROR TransportResponseHandler: Still have 1 requests outstanding when connection from 10.136.159.133/10.136.159.133:8080 is closed
16/08/02 19:19:30 WARN Worker: Failed to connect to master 10.136.159.133:8080
java.io.IOException: Connection from 10.136.159.133/10.136.159.133:8080 closed
        at org.apache.spark.network.client.TransportResponseHandler.channelUnregistered(TransportResponseHandler.java:124)
        at org.apache.spark.network.server.TransportChannelHandler.channelUnregistered(TransportChannelHandler.java:94)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:158)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:144)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:158)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:144)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:158)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:144)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:158)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:144)
        at io.netty.channel.DefaultChannelPipeline.fireChannelUnregistered(DefaultChannelPipeline.java:739)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:659)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:357)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
        at java.lang.Thread.run(Thread.java:722)
16/08/02 19:19:42 INFO Worker: Retrying connection to master (attempt # 1)
16/08/02 19:19:42 INFO Worker: Connecting to master 10.136.159.133:8080...
16/08/02 19:19:42 INFO TransportClientFactory: Found inactive connection to /10.136.159.133:8080, creating a new one.
16/08/02 19:19:42 ERROR TransportResponseHandler: Still have 1 requests outstanding when connection from 10.136.159.133/10.136.159.133:8080 is closed
16/08/02 19:19:42 WARN Worker: Failed to connect to master 10.136.159.133:8080
java.io.IOException: Connection from 10.136.159.133/10.136.159.133:8080 closed
        at org.apache.spark.network.client.TransportResponseHandler.channelUnregistered(TransportResponseHandler.java:124)
        at org.apache.spark.network.server.TransportChannelHandler.channelUnregistered(TransportChannelHandler.java:94)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:158)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:144)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:158)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:144)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:158)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:144)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:158)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:144)
        at io.netty.channel.DefaultChannelPipeline.fireChannelUnregistered(DefaultChannelPipeline.java:739)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:659)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:357)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
        at java.lang.Thread.run(Thread.java:722)
[root@Slave1 logs]#

**Comment by chris0927** [comment]
@n080509  you have been solved?

**Comment by q5390498** [comment]
i had the same problem,and i don't know how to slove it ,so ,can you ask me how to slove it? @n080509

**Comment by n080509** [comment]
No,I haven’t slove this problem

发件人: q5390498 [mailto:notifications@github.com]
发送时间: 2016年11月29日 10:28
收件人: yahoo/CaffeOnSpark
抄送: Gongxiangyu; Mention
主题: Re: [yahoo/CaffeOnSpark] run CaffeOnSpark standalone cluster,ERROR scheduler.TaskSchedulerImpl: Lost executor 2 on 10.136.159.133: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for ...


i had the same problem,and i don't know how to slove it ,so ,can you ask me how to slove it? @n080509<https://github.com/n080509>
