### ISSUE TITLE
MNIST LMDB failed in test step

### ISSUE THREAD

**Issue by markyeh** [yahoo/CaffeOnSpark#150]
Hi guys,

I tested the latest version with Spark 1.6.1.
Date:   Wed Sep 7 15:55:16 2016 -0700

MNIST dataframe is working fine, but MNIST LMDB got failed in test step.
Error message:
Caused by: org.apache.spark.SparkException: File /home/hadoop/hadoop/tmp/nm-local-dir/usercache/root/appcache/application_1473726027297_0003/spark-a7e004aa-a656-46f1-a507-4dc348cb9849/userFiles-a731a7d9-c6ca-48fd-946b-cbb950cc9ea9/mnist_test_lmdb/lock.mdb exists and does not match contents of hdfs://d3.bd.com:9000/mnist_test_lmdb/lock.mdb
[yarn_error_logs.txt](https://github.com/yahoo/CaffeOnSpark/files/468637/yarn_error_logs.txt)

**Comment by junshi15** [comment]
It is complaining that lock file. Maybe you need to delete lock.mdb file before you run the test.

**Comment by anfeng** [comment]
I think that you may have found an interesting corner case.

Can you explain the set of commands you executed? We could then add some
logic to resolve it.

Andy

Andy

**Comment by markyeh** [comment]
Hi junshi15,
I still got similar error when I deleted the lock.mdb.

Hi Andy,
Here is the command I ran for my test. 
And I did not meet this issue on older version (April and May).
Hope this information would be helpful, thanks.

spark-submit --master yarn --deploy-mode cluster \
--files /home/hadoop/mnist/lenet_memory_solver.prototxt,/home/hadoop/mnist/lenet_memory_train_test.prototxt \
--conf spark.driver.extraLibraryPath="${LD_LIBRARY_PATH}" \
--conf spark.executorEnv.LD_LIBRARY_PATH="${LD_LIBRARY_PATH}" \
--num-executors 2 \
--driver-memory 10G \
--executor-memory 70G \
--class com.yahoo.ml.caffe.CaffeOnSpark \
/home/hadoop/rebuild_gpu_907/caffe-grid-0.1-SNAPSHOT-jar-with-dependencies.jar \
-train \
-features accuracy,loss -label label \
-conf lenet_memory_solver.prototxt \
-devices 1 \
-connection ethernet \
-model hdfs:///output/mnist.model \
-output hdfs:///output/mnist_features_result

**Comment by anfeng** [comment]
please try out pull request #151

**Comment by junshi15** [comment]
I have merged the PR, please update your source code.

**Comment by markyeh** [comment]
Hi guys,

I got different errors with the latest version.
I'm not sure what's wrong, please take a look.

```
[root@hadoop]# yarn logs -applicationId application_1473726027297_0025
16/09/20 14:04:05 INFO client.RMProxy: Connecting to ResourceManager at d3.bd.com/10.0.0.3:8032
16/09/20 14:04:05 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable


Container: container_1473726027297_0025_01_000001 on d3.bd.com_41664
======================================================================
LogType:stderr
Log Upload Time:Tue Sep 20 13:58:42 +0000 2016
LogLength:3095
Log Contents:
16/09/20 13:58:36 INFO yarn.ApplicationMaster: Registered signal handlers for [TERM, HUP, INT]
16/09/20 13:58:37 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/09/20 13:58:37 INFO yarn.ApplicationMaster: ApplicationAttemptId: appattempt_1473726027297_0025_000001
16/09/20 13:58:38 INFO spark.SecurityManager: Changing view acls to: root
16/09/20 13:58:38 INFO spark.SecurityManager: Changing modify acls to: root
16/09/20 13:58:38 INFO spark.SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(root); users with modify permissions: Set(root)
16/09/20 13:58:38 INFO yarn.ApplicationMaster: Starting the user application in a separate Thread
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/sql/expressions/UserDefinedFunction
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2570)
        at java.lang.Class.getMethod0(Class.java:2813)
        at java.lang.Class.getMethod(Class.java:1663)
        at org.apache.spark.deploy.yarn.ApplicationMaster.startUserApplication(ApplicationMaster.scala:537)
        at org.apache.spark.deploy.yarn.ApplicationMaster.runDriver(ApplicationMaster.scala:319)
        at org.apache.spark.deploy.yarn.ApplicationMaster.run(ApplicationMaster.scala:185)
        at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$main$1.apply$mcV$sp(ApplicationMaster.scala:653)
        at org.apache.spark.deploy.SparkHadoopUtil$$anon$1.run(SparkHadoopUtil.scala:69)
        at org.apache.spark.deploy.SparkHadoopUtil$$anon$1.run(SparkHadoopUtil.scala:68)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
        at org.apache.spark.deploy.SparkHadoopUtil.runAsSparkUser(SparkHadoopUtil.scala:68)
        at org.apache.spark.deploy.yarn.ApplicationMaster$.main(ApplicationMaster.scala:651)
        at org.apache.spark.deploy.yarn.ApplicationMaster.main(ApplicationMaster.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.expressions.UserDefinedFunction
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 16 more
16/09/20 13:58:39 INFO yarn.ApplicationMaster: Final app status: SUCCEEDED, exitCode: 0, (reason: Shutdown hook called before final status was reported.)
16/09/20 13:58:39 INFO yarn.ApplicationMaster: Unregistering ApplicationMaster with SUCCEEDED (diag message: Shutdown hook called before final status was reported.)
16/09/20 13:58:39 INFO yarn.ApplicationMaster: Deleting staging directory .sparkStaging/application_1473726027297_0025
16/09/20 13:58:39 INFO util.ShutdownHookManager: Shutdown hook called
End of LogType:stderr

LogType:stdout
Log Upload Time:Tue Sep 20 13:58:42 +0000 2016
LogLength:0
Log Contents:
End of LogType:stdout
```

**Comment by markyeh** [comment]
This issue is fixed, thanks.
