### ISSUE TITLE
MNIST Example failure during training

### ISSUE THREAD

**Issue by dumoulma** [yahoo/CaffeOnSpark#152]
Hi!

Having a problem with running the mnist example. Caffe is compiled and runs fine, CaffeOnSpark compilation 100% perfect no issues. I'm running on a MapR cluster v5.2 (latest) with Spark 1.6.1. I have got a previous version of CaffeOnSpark running on two previous clusters (AWS and on premise hardware) before.

Just following the YARN instructions, modified lenet_memory_train_test.prototxt to point to hdfs for the input files, which were built exactly as recommended from the instructions in the wiki.

After about 5-10m of running smoothly (or so it seems) I get:
16/09/15 08:27:13 ERROR ApplicationMaster: User class threw exception: org.apache.spark.sql.catalyst.errors.package$TreeNodeException: execute, tree:

the full log: http://pastebin.com/eks4XYcJ
the most suspicious line looks to be this one: 
Caused by: org.apache.spark.SparkException: File /tmp/hadoop-mapr/nm-local-dir/usercache/mapr/appcache/application_1473925748984_0006/spark-8105925e-5d4d-4799-8f3d-e51e97b1be44/userFiles-a3ebee76-db7f-4214-9361-0a4ae63fbe89/mnist_test_lmdb/lock.mdb exists and does not match contents of hdfs:///projects/machine_learning/image_dataset/mnist_test_lmdb/lock.mdb

Any ideas?

**Comment by dumoulma** [comment]
![screen shot 2016-09-15 at 6 06 12 pm](https://cloud.githubusercontent.com/assets/3534929/18544362/30207774-7b6f-11e6-8501-a93c69eafbe6.png)
![screen shot 2016-09-15 at 6 06 41 pm](https://cloud.githubusercontent.com/assets/3534929/18544366/35bcfe8c-7b6f-11e6-8ce6-31bfb7247f8c.png)
![screen shot 2016-09-15 at 6 06 32 pm](https://cloud.githubusercontent.com/assets/3534929/18544378/3ecf5cfe-7b6f-11e6-9d3a-c8edda68def2.png)

**Comment by anfeng** [comment]
please try out pull request #151. It should address this problem.

**Comment by junshi15** [comment]
I have merged the PR, try the latest code.

**Comment by dumoulma** [comment]
Trying it today I'll let you know the result. Thanks a lot! you guys are really on top of your stuff.

**Comment by dumoulma** [comment]
Compilation and tests pass 100% AFAICS

**Comment by dumoulma** [comment]
Same problem, unfortunately :-(

16/09/16 02:57:32 ERROR ApplicationMaster: User class threw exception: org.apache.spark.sql.catalyst.errors.package$TreeNodeException: execute, tree:
TungstenAggregate(key=[], functions=[(count(1),mode=Final,isDistinct=false)], output=[count#36L])
+- TungstenExchange SinglePartition, None
   +- TungstenAggregate(key=[], functions=[(count(1),mode=Partial,isDistinct=false)], output=[count#59L])
      +- InMemoryColumnarTableScan InMemoryRelation [SampleID#12,accuracy#13,loss#14,label#15], true, 10000, StorageLevel(true, false, false, false, 1), ConvertToUnsafe, None

org.apache.spark.sql.catalyst.errors.package$TreeNodeException: execute, tree:
TungstenAggregate(key=[], functions=[(count(1),mode=Final,isDistinct=false)], output=[count#36L])
+- TungstenExchange SinglePartition, None
   +- TungstenAggregate(key=[], functions=[(count(1),mode=Partial,isDistinct=false)], output=[count#59L])
      +- InMemoryColumnarTableScan InMemoryRelation [SampleID#12,accuracy#13,loss#14,label#15], true, 10000, StorageLevel(true, false, false, false, 1), ConvertToUnsafe, None

	at org.apache.spark.sql.catalyst.errors.package$.attachTree(package.scala:49)
	at org.apache.spark.sql.execution.aggregate.TungstenAggregate.doExecute(TungstenAggregate.scala:80)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:132)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:130)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:130)
	at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:166)
	at org.apache.spark.sql.execution.SparkPlan.executeCollectPublic(SparkPlan.scala:174)
	at org.apache.spark.sql.DataFrame$$anonfun$org$apache$spark$sql$DataFrame$$execute$1$1.apply(DataFrame.scala:1499)
	at org.apache.spark.sql.DataFrame$$anonfun$org$apache$spark$sql$DataFrame$$execute$1$1.apply(DataFrame.scala:1499)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:56)
	at org.apache.spark.sql.DataFrame.withNewExecutionId(DataFrame.scala:2086)
	at org.apache.spark.sql.DataFrame.org$apache$spark$sql$DataFrame$$execute$1(DataFrame.scala:1498)
	at org.apache.spark.sql.DataFrame.org$apache$spark$sql$DataFrame$$collect(DataFrame.scala:1505)
	at org.apache.spark.sql.DataFrame$$anonfun$count$1.apply(DataFrame.scala:1515)
	at org.apache.spark.sql.DataFrame$$anonfun$count$1.apply(DataFrame.scala:1514)
	at org.apache.spark.sql.DataFrame.withCallback(DataFrame.scala:2099)
	at org.apache.spark.sql.DataFrame.count(DataFrame.scala:1514)
	at com.yahoo.ml.caffe.CaffeOnSpark.features(CaffeOnSpark.scala:432)
	at com.yahoo.ml.caffe.CaffeOnSpark$.main(CaffeOnSpark.scala:54)
	at com.yahoo.ml.caffe.CaffeOnSpark.main(CaffeOnSpark.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:542)
Caused by: org.apache.spark.sql.catalyst.errors.package$TreeNodeException: execute, tree:
TungstenExchange SinglePartition, None
+- TungstenAggregate(key=[], functions=[(count(1),mode=Partial,isDistinct=false)], output=[count#59L])
   +- InMemoryColumnarTableScan InMemoryRelation [SampleID#12,accuracy#13,loss#14,label#15], true, 10000, StorageLevel(true, false, false, false, 1), ConvertToUnsafe, None

	at org.apache.spark.sql.catalyst.errors.package$.attachTree(package.scala:49)
	at org.apache.spark.sql.execution.Exchange.doExecute(Exchange.scala:247)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:132)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:130)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:130)
	at org.apache.spark.sql.execution.aggregate.TungstenAggregate$$anonfun$doExecute$1.apply(TungstenAggregate.scala:86)
	at org.apache.spark.sql.execution.aggregate.TungstenAggregate$$anonfun$doExecute$1.apply(TungstenAggregate.scala:80)
	at org.apache.spark.sql.catalyst.errors.package$.attachTree(package.scala:48)
	... 25 more
Caused by: org.apache.spark.SparkException: File /tmp/hadoop-mapr/nm-local-dir/usercache/mapr/appcache/application_1473992492491_0002/spark-de292376-ec71-4a8f-b932-f8c3d2ad6698/userFiles-f91d0e60-1440-4c2b-bcec-35c6fe61d9d9/mnist_test_lmdb/lock.mdb exists and does not match contents of hdfs:///projects/machine_learning/image_dataset/mnist_test_lmdb/lock.mdb
	at org.apache.spark.util.Utils$.copyFile(Utils.scala:489)
	at org.apache.spark.util.Utils$.downloadFile(Utils.scala:441)
	at org.apache.spark.util.Utils$.fetchHcfsFile(Utils.scala:624)
	at org.apache.spark.util.Utils$$anonfun$fetchHcfsFile$1.apply(Utils.scala:630)
	at org.apache.spark.util.Utils$$anonfun$fetchHcfsFile$1.apply(Utils.scala:629)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at org.apache.spark.util.Utils$.fetchHcfsFile(Utils.scala:629)
	at org.apache.spark.util.Utils$.doFetchFile(Utils.scala:599)
	at org.apache.spark.util.Utils$.fetchFile(Utils.scala:394)
	at org.apache.spark.SparkContext.addFile(SparkContext.scala:1386)
	at com.yahoo.ml.caffe.LmdbRDD.getPartitions(LmdbRDD.scala:46)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.ShuffleDependency.<init>(Dependency.scala:91)
	at org.apache.spark.sql.execution.Exchange.prepareShuffleDependency(Exchange.scala:220)
	at org.apache.spark.sql.execution.Exchange$$anonfun$doExecute$1.apply(Exchange.scala:254)
	at org.apache.spark.sql.execution.Exchange$$anonfun$doExecute$1.apply(Exchange.scala:248)
	at org.apache.spark.sql.catalyst.errors.package$.attachTree(package.scala:48)

![screen shot 2016-09-16 at 12 04 09 pm](https://cloud.githubusercontent.com/assets/3534929/18574198/b4a07c10-7c05-11e6-8a18-35bb49c254b5.png)

**Comment by dumoulma** [comment]
Please let me know if there are any other logs you would like me to post if it can help in any way.

**Comment by anfeng** [comment]
@dumoulma  I set a wrong config object. Please try to pull my latest code at branch afeng_avoid_lock_mdb via: git pull origin afeng_avoid_lock_mdb

I have opened a new PR #154. Please comment there.

**Comment by anfeng** [comment]
We have merged PR #155, which should fixed your issue.

**Comment by dumoulma** [comment]
I confirm the issue is fixed. thanks again.
