### ISSUE TITLE
Error while encoding: java.lang.RuntimeException: java.lang.String is not a valid external type for schema of bigint

### ISSUE THREAD

**Issue by liuguiyangnwpu** [yahoo/CaffeOnSpark#184]
```
2016-11-12 23:21:56,162 [Executor task launch worker-1] INFO  codegen.CodeGenerator - Code generated in 21.033996 ms
2016-11-12 23:21:56,177 [Executor task launch worker-1] INFO  codegen.CodeGenerator - Code generated in 8.726763 ms
2016-11-12 23:21:56,182 [Executor task launch worker-1] ERROR executor.Executor - Exception in task 1.0 in stage 58.0 (TID 43)
java.lang.RuntimeException: Error while encoding: java.lang.RuntimeException: java.lang.String is not a valid external type for schema of bigint
if (assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object).isNullAt) null else validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 0, id), LongType) AS id#161L
+- if (assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object).isNullAt) null else validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 0, id), LongType)
   :- assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object).isNullAt
   :  :- assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object)
   :  :  +- input[0, org.apache.spark.sql.Row, true]
   :  +- 0
   :- null
   +- validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 0, id), LongType)
      +- getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 0, id)
         +- assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object)
            +- input[0, org.apache.spark.sql.Row, true]

if (assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object).isNullAt) null else staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 1, caption), StringType), true) AS caption#162
+- if (assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object).isNullAt) null else staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 1, caption), StringType), true)
   :- assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object).isNullAt
   :  :- assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object)
   :  :  +- input[0, org.apache.spark.sql.Row, true]
   :  +- 1
   :- null
   +- staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 1, caption), StringType), true)
      +- validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 1, caption), StringType)
         +- getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 1, caption)
            +- assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object)
               +- input[0, org.apache.spark.sql.Row, true]

	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder.toRow(ExpressionEncoder.scala:279)
	at org.apache.spark.sql.SparkSession$$anonfun$5.apply(SparkSession.scala:537)
	at org.apache.spark.sql.SparkSession$$anonfun$5.apply(SparkSession.scala:537)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:370)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:389)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
	at scala.collection.AbstractIterator.to(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1336)
	at org.apache.spark.rdd.RDD$$anonfun$take$1$$anonfun$29.apply(RDD.scala:1324)
	at org.apache.spark.rdd.RDD$$anonfun$take$1$$anonfun$29.apply(RDD.scala:1324)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1916)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1916)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:86)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.String is not a valid external type for schema of bigint
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder.toRow(ExpressionEncoder.scala:276)
	... 32 more
2016-11-12 23:21:56,192 [dispatcher-event-loop-3] INFO  scheduler.TaskSetManager - Starting task 2.0 in stage 58.0 (TID 44, localhost, partition 3, PROCESS_LOCAL, 5244 bytes)
2016-11-12 23:21:56,192 [Executor task launch worker-1] INFO  executor.Executor - Running task 2.0 in stage 58.0 (TID 44)
2016-11-12 23:21:56,194 [task-result-getter-3] WARN  scheduler.TaskSetManager - Lost task 1.0 in stage 58.0 (TID 43, localhost): java.lang.RuntimeException: Error while encoding: java.lang.RuntimeException: java.lang.String is not a valid external type for schema of bigint
if (assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object).isNullAt) null else validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 0, id), LongType) AS id#161L
+- if (assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object).isNullAt) null else validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 0, id), LongType)
   :- assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object).isNullAt
   :  :- assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object)
   :  :  +- input[0, org.apache.spark.sql.Row, true]
   :  +- 0
   :- null
   +- validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 0, id), LongType)
      +- getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 0, id)
         +- assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object)
            +- input[0, org.apache.spark.sql.Row, true]

if (assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object).isNullAt) null else staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 1, caption), StringType), true) AS caption#162
+- if (assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object).isNullAt) null else staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 1, caption), StringType), true)
   :- assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object).isNullAt
   :  :- assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object)
   :  :  +- input[0, org.apache.spark.sql.Row, true]
   :  +- 1
   :- null
   +- staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 1, caption), StringType), true)
      +- validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 1, caption), StringType)
         +- getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 1, caption)
            +- assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object)
               +- input[0, org.apache.spark.sql.Row, true]

	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder.toRow(ExpressionEncoder.scala:279)
	at org.apache.spark.sql.SparkSession$$anonfun$5.apply(SparkSession.scala:537)
	at org.apache.spark.sql.SparkSession$$anonfun$5.apply(SparkSession.scala:537)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:370)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:389)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
	at scala.collection.AbstractIterator.to(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1336)
	at org.apache.spark.rdd.RDD$$anonfun$take$1$$anonfun$29.apply(RDD.scala:1324)
	at org.apache.spark.rdd.RDD$$anonfun$take$1$$anonfun$29.apply(RDD.scala:1324)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1916)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1916)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:86)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.String is not a valid external type for schema of bigint
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder.toRow(ExpressionEncoder.scala:276)
	... 32 more

2016-11-12 23:21:56,195 [task-result-getter-3] ERROR scheduler.TaskSetManager - Task 1 in stage 58.0 failed 1 times; aborting job
2016-11-12 23:21:56,195 [Executor task launch worker-1] INFO  storage.ShuffleBlockFetcherIterator - Getting 1 non-empty blocks out of 4 blocks
2016-11-12 23:21:56,197 [Executor task launch worker-1] INFO  storage.ShuffleBlockFetcherIterator - Started 0 remote fetches in 2 ms
2016-11-12 23:21:56,197 [Executor task launch worker-1] INFO  storage.ShuffleBlockFetcherIterator - Getting 1 non-empty blocks out of 4 blocks
2016-11-12 23:21:56,197 [Executor task launch worker-1] INFO  storage.ShuffleBlockFetcherIterator - Started 0 remote fetches in 0 ms
2016-11-12 23:21:56,199 [dag-scheduler-event-loop] INFO  scheduler.TaskSchedulerImpl - Cancelling stage 58
2016-11-12 23:21:56,200 [dispatcher-event-loop-1] INFO  executor.Executor - Executor is trying to kill task 2.0 in stage 58.0 (TID 44)
2016-11-12 23:21:56,201 [dag-scheduler-event-loop] INFO  scheduler.TaskSchedulerImpl - Stage 58 was cancelled
```

**Comment by liuguiyangnwpu** [comment]
```
2016-11-12 23:21:56,209 [ScalaTest-main-running-DiscoverySuite] INFO  handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@3b66ac74{/jobs,null,UNAVAILABLE}
[31m- CocoTest *** FAILED ***[0m
[31m  org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 58.0 failed 1 times, most recent failure: Lost task 1.0 in stage 58.0 (TID 43, localhost): java.lang.RuntimeException: Error while encoding: java.lang.RuntimeException: java.lang.String is not a valid external type for schema of bigint[0m
[31mif (assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object).isNullAt) null else validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 0, id), LongType) AS id#161L[0m
[31m+- if (assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object).isNullAt) null else validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 0, id), LongType)[0m
[31m   :- assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object).isNullAt[0m
[31m   :  :- assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object)[0m
[31m   :  :  +- input[0, org.apache.spark.sql.Row, true][0m
[31m   :  +- 0[0m
[31m   :- null[0m
[31m   +- validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 0, id), LongType)[0m
[31m      +- getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 0, id)[0m
[31m         +- assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object)[0m
[31m            +- input[0, org.apache.spark.sql.Row, true][0m
[31m[0m
[31mif (assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object).isNullAt) null else staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 1, caption), StringType), true) AS caption#162[0m
[31m+- if (assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object).isNullAt) null else staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 1, caption), StringType), true)[0m
[31m   :- assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object).isNullAt[0m
[31m   :  :- assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object)[0m
[31m   :  :  +- input[0, org.apache.spark.sql.Row, true][0m
[31m   :  +- 1[0m
[31m   :- null[0m
[31m   +- staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 1, caption), StringType), true)[0m
[31m      +- validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 1, caption), StringType)[0m
[31m         +- getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 1, caption)[0m
[31m            +- assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object)[0m
[31m               +- input[0, org.apache.spark.sql.Row, true][0m
[31m[0m
[31m	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder.toRow(ExpressionEncoder.scala:279)[0m
```

**Comment by liuguiyangnwpu** [comment]
Hi,
I use Software Version:
```
Centos 7.2.1511
hadoop-2.7.3
Spark-2.0.1
Scala-2.11.8
mvn-3.3.9
```

In the ```/etc/environment```, i changed the LANG=en_US.utf-8.
What should  I do ?

thx !

**Comment by junshi15** [comment]
How did you get the errors? What kind of training or test were you running?

**Comment by liuguiyangnwpu** [comment]
hi,
I use make build command to compile this projects.
And I found the command in the Makefile is 
```
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH2}"; GLOG_minloglevel=1 mvn ${MVN_SPARK_FLAG} -B test
```
The total result 
```
2016-11-12 23:22:06,900 [Thread-2] INFO  util.ShutdownHookManager - Shutdown hook called
2016-11-12 23:22:06,901 [Thread-2] INFO  util.ShutdownHookManager - Deleting directory /tmp/spark-2ae56acd-0079-4392-bffb-eb3ec2bb6a46
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] caffe .............................................. SUCCESS [  0.002 s]
[INFO] caffe-distri ....................................... SUCCESS [02:26 min]
[INFO] caffe-grid ......................................... FAILURE [ 23.581 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:50 min
[INFO] Finished at: 2016-11-12T23:22:06+08:00
[INFO] Final Memory: 32M/593M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.scalatest:scalatest-maven-plugin:1.0:test (test) on project caffe-grid: There are test failures -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.scalatest:scalatest-maven-plugin:1.0:test (test) on project caffe-grid: There are test failures
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures
	at org.scalatest.tools.maven.TestMojo.execute(TestMojo.java:107)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :caffe-grid
```

**Comment by junshi15** [comment]
Not sure where the problem is. But the last PR passed Travis with no problem.
https://github.com/yahoo/CaffeOnSpark/pull/176

**Comment by javimol** [comment]
Hello @liuguiyangnwpu,
   I am facing the same error when compiling CaffeOnSpark. I was wondering... did you manage to solve it?or did you managed to get any useful information?
Thanks in advance!

**Comment by liuguiyangnwpu** [comment]
hello @javimol ,
I find this error is only occurs in the test case, and Caused by the Encoding, this maybe the BigInt vs UTF-8 encoding error. Maybe occures by the scala, when I comment the Test Case, I finished the build, And Can Run the Below Command about the Python !

In the Makefile,
```
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH2}"; GLOG_minloglevel=1 mvn ${MVN_SPARK_FLAG} -B test
```
I change it in this way,
```
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH2}"; 
#GLOG_minloglevel=1 mvn ${MVN_SPARK_FLAG} -B test
```

```
make build
```

**Comment by javimol** [comment]
Thanks so much @liuguiyangnwpu, I'll try to put CaffeOnSpark on work "ignoring" this test failure.

**Comment by chris0927** [comment]
When I make build,I have this error.

**Comment by summerspringwei** [comment]
It seems that in Spark, primary data type should be convert to corresponding DataType in [org.apache.spark.sql.types]. 
for example, 'String' in scala can be converted to StringType in Spark, while can not be converted to LongType in Spark, and 'Long' can.'
originally:
`val inventoryDataType = Array(LongType, LongType, LongType, IntegerType)`
...
`// Convert records of the RDD (inventory) to Rows
    val rowRDD = inventoryRDD
      .map(_.split(",").toSeq)
      .map(attributes => {
        Row(attributes(0).trim, attributes(1).trim, attributes(2).trim, attributes(3).trim)
      })
`
I got errors like you. Then, I changed the 

then I change the code like these below:
`// Convert records of the RDD (inventory) to Rows
    val rowRDD = inventoryRDD
      .map(_.split(",").toSeq)
      .map(attributes => {
        Row(attributes(0).trim.toLong, attributes(1).trim.toLong, attributes(2).trim.toLong, attributes(3).trim.toInt)
      })`
It works!

**Comment by xye43** [comment]
@summerspringwei where is the code?
