### ISSUE TITLE
How to know that CaffeOnSpark is running in GPU mode?

### ISSUE THREAD

**Issue by chris0927** [yahoo/CaffeOnSpark#199]
16/11/28 15:55:37 ERROR scheduler.TaskSchedulerImpl: Lost executor 3 on 10.11.35.201: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
16/11/28 15:55:37 WARN scheduler.TaskSetManager: Lost task 0.3 in stage 2.0 (TID 5, 10.11.35.201): ExecutorLostFailure (executor 3 exited caused by one of the running tasks) Reason: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
16/11/28 15:55:37 ERROR scheduler.TaskSetManager: Task 0 in stage 2.0 failed 4 times; aborting job
16/11/28 15:55:37 INFO scheduler.TaskSchedulerImpl: Removed TaskSet 2.0, whose tasks have all completed, from pool 
16/11/28 15:55:37 INFO client.StandaloneAppClient$ClientEndpoint: Executor updated: app-20161128155316-0033/3 is now EXITED (Command exited with code 134)
16/11/28 15:55:37 INFO cluster.StandaloneSchedulerBackend: Executor app-20161128155316-0033/3 removed: Command exited with code 134
16/11/28 15:55:37 INFO storage.BlockManagerMasterEndpoint: Trying to remove executor 3 from BlockManagerMaster.
16/11/28 15:55:37 INFO storage.BlockManagerMaster: Removal of executor 3 requested
16/11/28 15:55:37 INFO cluster.CoarseGrainedSchedulerBackend$DriverEndpoint: Asked to remove non-existent executor 3
16/11/28 15:55:37 INFO storage.BlockManagerMasterEndpoint: Removing block manager BlockManagerId(3, 10.11.35.201, 53747)
16/11/28 15:55:37 INFO client.StandaloneAppClient$ClientEndpoint: Executor added: app-20161128155316-0033/4 on worker-20161128141254-10.11.35.201-59582 (10.11.35.201:59582) with 1 cores
16/11/28 15:55:37 INFO scheduler.TaskSchedulerImpl: Cancelling stage 2
16/11/28 15:55:37 INFO cluster.StandaloneSchedulerBackend: Granted executor ID app-20161128155316-0033/4 on hostPort 10.11.35.201:59582 with 1 cores, 1024.0 MB RAM
16/11/28 15:55:37 INFO scheduler.DAGScheduler: ResultStage 2 (collect at CaffeOnSpark.scala:123) failed in 97.901 s
16/11/28 15:55:37 INFO scheduler.DAGScheduler: Job 2 failed: collect at CaffeOnSpark.scala:123, took 97.924149 s
16/11/28 15:55:37 INFO scheduler.DAGScheduler: Executor lost: 3 (epoch 3)
16/11/28 15:55:37 INFO storage.BlockManagerMasterEndpoint: Trying to remove executor 3 from BlockManagerMaster.
Exception in thread "main" 16/11/28 15:55:37 INFO storage.BlockManagerMaster: Removed 3 successfully in removeExecutor
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 2.0 failed 4 times, most recent failure: Lost task 0.3 in stage 2.0 (TID 5, 10.11.35.201): ExecutorLostFailure (executor 3 exited caused by one of the running tasks) Reason: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1450)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1438)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1437)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1437)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:811)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1659)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1618)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1607)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:632)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1871)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1884)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1897)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1911)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:893)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:358)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:892)
	at com.yahoo.ml.caffe.CaffeOnSpark.setupTraining(CaffeOnSpark.scala:123)
	at com.yahoo.ml.caffe.CaffeOnSpark.trainWithValidation(CaffeOnSpark.scala:276)
	at com.yahoo.ml.caffe.CaffeOnSpark$.main(CaffeOnSpark.scala:42)
	at com.yahoo.ml.caffe.CaffeOnSpark.main(CaffeOnSpark.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:729)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
16/11/28 15:55:37 INFO client.StandaloneAppClient$ClientEndpoint: Executor updated: app-20161128155316-0033/4 is now RUNNING

This is the error in GPU mode,cpu is ok!

**Comment by junshi15** [comment]
This driver log says Executor #3 died. More information should be in the corresponding executor log. I suspect GPU was not available on that node for some reason.

**Comment by chris0927** [comment]
@junshi15  yes,GPU was not available on that node.

**Comment by junshi15** [comment]
GPU/CPU mode is set in the solver prototxt file, e.g.
https://github.com/yahoo/CaffeOnSpark/blob/master/data/lenet_memory_solver.prototxt#L23

If you set GPU mode, but the nodes do not have GPUs, then program will abort.

**Comment by chris0927** [comment]
I rebuild,then it`s ok.
