### ISSUE TITLE
Error in Train a DNN network using CaffeOnSpark with 2 Spark executors

### ISSUE THREAD

**Issue by malia05** [yahoo/CaffeOnSpark#226]
Hi, after successful build  of my CaffeOnSpark, 
./spark-submit --master ${MASTER_URL} \
>     --files ${CAFFE_ON_SPARK}/data/lenet_memory_solver.prototxt,${CAFFE_ON_SPARK}/data/lenet_memory_train_test.prototxt \
>     --conf spark.cores.max=${TOTAL_CORES} \
>     --conf spark.task.cpus=${CORES_PER_WORKER} \
>     --conf spark.driver.extraLibraryPath="${LD_LIBRARY_PATH}" \
>     --conf spark.executorEnv.LD_LIBRARY_PATH="${LD_LIBRARY_PATH}" \
>     --class com.yahoo.ml.caffe.CaffeOnSpark  \
>     ${CAFFE_ON_SPARK}/caffe-grid/target/caffe-grid-0.1-SNAPSHOT-jar-with-dependencies.jar \
>         -train \
>         -features accuracy,loss -label label \
>         -conf lenet_memory_solver.prototxt \
>     -clusterSize ${SPARK_WORKER_INSTANCES} \
>         -devices 1 \
>     -connection ethernet \
>         -model file:${CAFFE_ON_SPARK}/mnist_lenet.model \
>         -output file:${CAFFE_ON_SPARK}/lenet_features_result
An error displayed, which said:
 Error: Cannot load main class from JAR file:/data/lenet_memory_solver.prototxt,/data/lenet_memory_train_test.prototxt Run with --help for usage help or --verbose for debug output
Can someone help me plz, and thanks so much

**Comment by baristahell** [comment]
Seems like it mixes up the prototxts and caffe-grid-0.1-SNAPSHOT-jar-with-dependencies.jar
What are your ENV variables? 
What kind of cluster are you working on? The default from the wiki page?

**Comment by malia05** [comment]
I try for the second time in standalone mode to train on spark  the mnist data using: ./bin/spark-submit --master local[4] --files ${CAFFE_ON_SPARK}/data/lenet_memory_solver.prototxt,${CAFFE_ON_SPARK}/data/lenet_memory_train_test.prototxt --conf spark.driver.extraLibraryPath="${DYLD_LIBRARY_PATH}" --conf spark.executorEnv.DYLD_LIBRARY_PATH="${DYLD_LIBRARY_PATH}" --class com.yahoo.ml.caffe.CaffeOnSpark ${CAFFE_ON_SPARK}/caffe-grid/target/caffe-grid-0.1-SNAPSHOT-jar-with-dependencies.jar -train -features accuracy,loss -label label -conf lenet_memory_solver.prototxt -connection ethernet -model file:${CAFFE_ON_SPARK}/mnist_lenet.model -output file:${CAFFE_ON_SPARK}/lenet_features_result
I have this error: Warning: Local jar /caffe-grid/target/caffe-grid-0.1-SNAPSHOT-jar-with-dependencies.jar does not exist, skipping.
java.lang.ClassNotFoundException: com.yahoo.ml.caffe.CaffeOnSpark
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.spark.util.Utils$.classForName(Utils.scala:174)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:689)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
plz baristahell help me....
