### ISSUE TITLE
Train on 200G dataset but total memory is 150G

### ISSUE THREAD

**Issue by haikuoyao** [yahoo/CaffeOnSpark#234]
I tried to train Alexnet on 200G dataset on CaffeOnSpark. My total memory of cluster is 150G.
**Can I train it ?** Do I have to keep memory larger than dataset ?

I always get this error and seems the memory isn't enough.

```
17/03/07 10:53:23 INFO caffe.LmdbRDD: Processing partition 42
17/03/07 10:53:23 INFO caffe.LmdbRDD: local LMDB path:/home/hk/data/hadoop/yarn/local/usercache/hk/appcache/application_1487054604530_0231/container_1487054604530_0231_01_000002/./train_lmdb_0_1000
17/03/07 10:53:26 INFO executor.CoarseGrainedExecutorBackend: Driver commanded a shutdown
17/03/07 10:53:26 INFO executor.CoarseGrainedExecutorBackend: Driver from 10.32.174.143:37127 disconnected during shutdown
17/03/07 10:53:26 INFO executor.CoarseGrainedExecutorBackend: Driver from 10.32.174.143:37127 disconnected during shutdown
17/03/07 10:53:27 ERROR executor.CoarseGrainedExecutorBackend: RECEIVED SIGNAL TERM
17/03/07 10:53:27 INFO util.ShutdownHookManager: Shutdown hook called (edited)

[10:24]  
17/03/07 10:53:23 INFO cluster.YarnSchedulerBackend$YarnDriverEndpoint: Launching task 42 on executor id: 1 hostname: LNBOTBE1502.nhnjp.ism.
17/03/07 10:53:23 INFO scheduler.TaskSetManager: Finished task 41.0 in stage 0.0 (TID 41) in 3954 ms on LNBOTBE1502.nhnjp.ism (41/500)
17/03/07 10:53:26 ERROR yarn.ApplicationMaster: RECEIVED SIGNAL TERM
17/03/07 10:53:26 INFO spark.SparkContext: Invoking stop() from shutdown hook
17/03/07 10:53:26 INFO server.ServerConnector: Stopped ServerConnector@306c186f{HTTP/1.1}{0.0.0.0:0}
17/03/07 10:53:26 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@28f4e290{/stages/stage/kill,null,UNAVAILABLE}
```

Thanks.

**Comment by arundasan91** [comment]
In cases like these, it is not recommended to use  LMDB as such. This is because (if I am not wrong) the LMDB file needs to be transferred to all worker nodes. Please use [Dataframes](https://github.com/yahoo/CaffeOnSpark/wiki/GetStarted_EC2) instead.

**Comment by haikuoyao** [comment]
Thanks @arundasan91 . 

I tried to convert LMDB to DataFrame with [LMDB2DataFrame](https://github.com/yahoo/CaffeOnSpark/blob/master/caffe-grid/src/main/scala/com/yahoo/ml/caffe/tools/LMDB2DataFrame.scala) but I got an issue 
like this
```
17/03/09 15:26:25 INFO yarn.YarnAllocator: Submitted container request (host: Any, capability: <memory:40550, vCores:2>)
17/03/09 15:26:29 WARN server.TransportChannelHandler: Exception in connection from /10.3.1.142:59980
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:313)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:242)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at java.lang.Thread.run(Thread.java:745)
17/03/09 15:26:29 INFO cluster.YarnSchedulerBackend$YarnDriverEndpoint: Disabling executor 1.
```
Then job failed.

Did it happen when you converted LMDB ? 
Thanks a million.

**Comment by arundasan91** [comment]
HI @haikuoyao ,

This is the code snippet I ended up using to convert LMDB to dataframe. I've mentioned it in another similar issue.

```
pushd ${CAFFE_ON_SPARK}/data

hadoop fs -rm -r -f ${CAFFE_ON_SPARK}/data/mnist_train_dataframe
spark-submit --master ${MASTER_URL} \
         --conf spark.cores.max=${TOTAL_CORES} \
             --conf spark.driver.extraLibraryPath="${LD_LIBRARY_PATH}" \
             --conf spark.executorEnv.LD_LIBRARY_PATH="${LD_LIBRARY_PATH}" \
             --class com.yahoo.ml.caffe.tools.LMDB2DataFrame \
             ${CAFFE_ON_SPARK}/caffe-grid/target/caffe-grid-0.1-SNAPSHOT-jar-with-dependencies.jar \
             -imageRoot file:${CAFFE_ON_SPARK}/data/mnist_train_lmdb \
             -lmdb_partitions ${TOTAL_CORES} \
             -outputFormat parquet \
             -output ${CAFFE_ON_SPARK}/data/mnist_train_dataframe


hadoop fs -rm -r -f ${CAFFE_ON_SPARK}/data/mnist_test_dataframe
spark-submit --master ${MASTER_URL} \
         --conf spark.cores.max=${TOTAL_CORES} \
             --conf spark.driver.extraLibraryPath="${LD_LIBRARY_PATH}" \
             --conf spark.executorEnv.LD_LIBRARY_PATH="${LD_LIBRARY_PATH}" \
             --class com.yahoo.ml.caffe.tools.LMDB2DataFrame \
             ${CAFFE_ON_SPARK}/caffe-grid/target/caffe-grid-0.1-SNAPSHOT-jar-with-dependencies.jar \
             -imageRoot file:${CAFFE_ON_SPARK}/data/mnist_test_lmdb \
             -lmdb_partitions ${TOTAL_CORES} \
             -outputFormat parquet \
             -output ${CAFFE_ON_SPARK}/data/mnist_test_dataframe
```

If I remember correctly, you'll have to adapt if your LMDB files are in HDFS. That's the only catch here. The output will be in HDFS format as a dataframe. You can use `hadoop fs -ls` to view the files. For example `hadoop fs -ls ${CAFFE_ON_SPARK}/data/mnist_test_dataframe`.

In order to do this, you need a Spark cluster (not Yarn, I don't know how to do it Yarn). Use the usual steps:

```
export MASTER_URL=spark://arun-master:7077
export SPARK_WORKER_INSTANCES=5
export CORES_PER_WORKER=4 
export TOTAL_CORES=$((${CORES_PER_WORKER}*${SPARK_WORKER_INSTANCES})) 
${SPARK_HOME}/sbin/start-slave.sh -c $CORES_PER_WORKER -m 3G ${MASTER_URL}
```

I haven't used the [LMDB2DataFrame](https://github.com/yahoo/CaffeOnSpark/blob/master/caffe-grid/src/main/scala/com/yahoo/ml/caffe/tools/LMDB2DataFrame.scala) as such because I have less experience with Scala and Java. The steps mentioned above works like a charm. I've done the same using CIFAR10 dataset as well. Its basically a few lines of change from the above:

```
hadoop fs -rm -r -f ${CAFFE_ON_SPARK}/data/cifar10_test_dataframe
spark-submit --master ${MASTER_URL} \
         --conf spark.cores.max=${TOTAL_CORES} \
             --conf spark.driver.extraLibraryPath="${LD_LIBRARY_PATH}" \
             --conf spark.executorEnv.LD_LIBRARY_PATH="${LD_LIBRARY_PATH}" \
             --class com.yahoo.ml.caffe.tools.LMDB2DataFrame \
             ${CAFFE_ON_SPARK}/caffe-grid/target/caffe-grid-0.1-SNAPSHOT-jar-with-dependencies.jar \
             -imageRoot file:${CAFFE_ON_SPARK}/data/cifar10_test_lmdb \
             -lmdb_partitions ${TOTAL_CORES} \
             -outputFormat parquet \
             -output ${CAFFE_ON_SPARK}/data/cifar10_test_dataframe


hadoop fs -rm -r -f ${CAFFE_ON_SPARK}/data/cifar10_train_dataframe
spark-submit --master ${MASTER_URL} \
         --conf spark.cores.max=${TOTAL_CORES} \
             --conf spark.driver.extraLibraryPath="${LD_LIBRARY_PATH}" \
             --conf spark.executorEnv.LD_LIBRARY_PATH="${LD_LIBRARY_PATH}" \
             --class com.yahoo.ml.caffe.tools.LMDB2DataFrame \
             ${CAFFE_ON_SPARK}/caffe-grid/target/caffe-grid-0.1-SNAPSHOT-jar-with-dependencies.jar \
             -imageRoot file:${CAFFE_ON_SPARK}/data/cifar10_train_lmdb \
             -lmdb_partitions ${TOTAL_CORES} \
             -outputFormat parquet \
             -output ${CAFFE_ON_SPARK}/data/cifar10_train_dataframe
```

Hope this will help. Could you please try this out and let me know ? Also, when you have a chance, please educate me on running LMDB2Dataframe. :)

Thanks,
Arun

**Comment by haikuoyao** [comment]
hi @arundasan91 Thanks so so so much. :)

It works finally.  I converted LMDB to Dataframe first then trained with Dataframe.

1 `lmdb_partitions ` has to be set.
2 A huge disk space is needed when converting ImageNet LMDB. Our LMDB file is about 200G. We have to leave 800G on each data node
3 Then just submit spark job. 
:)
