### ISSUE TITLE
Does libcaffedistri.so dependent on libboost_system.so.1.54.0?

### ISSUE THREAD

**Issue by dejunzhang** [yahoo/CaffeOnSpark#27]
In a cluster envirement, after running below command:
spark-submit --master ${MASTER_URL}     --files ${CAFFE_ON_SPARK}/data/lenet_memory_solver.prototxt,${CAFFE_ON_SPARK}/data/lenet_memory_train_test.prototxt     --conf spark.cores.max=${TOTAL_CORES}     --conf spark.driver.extraLibraryPath="${LD_LIBRARY_PATH}"     --conf spark.executorEnv.LD_LIBRARY_PATH="${LD_LIBRARY_PATH}"     --class com.yahoo.ml.caffe.CaffeOnSpark      ${CAFFE_ON_SPARK}/caffe-grid/target/caffe-grid-0.1-SNAPSHOT-jar-with-dependencies.jar         -train         -features accuracy,loss -label label         -conf lenet_memory_solver.prototxt     -clusterSize ${SPARK_WORKER_INSTANCES}         -devices 1     -connection ethernet         -model file:${CAFFE_ON_SPARK}/mnist_lenet.model         -output file:${CAFFE_ON_SPARK}/lenet_features_result

the following error message appeared in the slave node logs.

6/03/15 19:26:44 INFO storage.MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 1910.0 B, free 4.8 KB)
16/03/15 19:26:44 INFO storage.BlockManagerInfo: Added broadcast_0_piece0 in memory on 10.110.52.32:44175 (size: 1910.0 B, free: 457.9 MB)
16/03/15 19:26:44 INFO spark.SparkContext: Created broadcast 0 from broadcast at DAGScheduler.scala:1006
16/03/15 19:26:44 INFO scheduler.DAGScheduler: Submitting 1 missing tasks from ResultStage 0 (MapPartitionsRDD[2] at map at CaffeOnSpark.scala:121)
16/03/15 19:26:44 INFO cluster.YarnClusterScheduler: Adding task set 0.0 with 1 tasks
16/03/15 19:26:44 INFO scheduler.TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0, yuntu2, partition 0,PROCESS_LOCAL, 1966 bytes)
16/03/15 19:26:44 INFO storage.BlockManagerInfo: Added broadcast_0_piece0 in memory on yuntu2:42173 (size: 1910.0 B, free: 511.5 MB)
16/03/15 19:26:45 WARN scheduler.TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0, yuntu2): java.lang.UnsatisfiedLinkError: /home/atlas/work/caffe_spark/CaffeOnSpark-master/caffe-distri/distribute/lib/libcaffedistri.so: libboost_system.so.1.54.0: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1880)
	at java.lang.Runtime.loadLibrary0(Runtime.java:849)
	at java.lang.System.loadLibrary(System.java:1088)
	at com.yahoo.ml.jcaffe.BaseObject.<clinit>(BaseObject.java:10)
	at com.yahoo.ml.caffe.CaffeProcessor.<init>(CaffeProcessor.scala:55)
	at com.yahoo.ml.caffe.CaffeProcessor$.instance(CaffeProcessor.scala:21)
	at com.yahoo.ml.caffe.CaffeOnSpark$$anonfun$4.apply(CaffeOnSpark.scala:123)
	at com.yahoo.ml.caffe.CaffeOnSpark$$anonfun$4.apply(CaffeOnSpark.scala:121)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:103)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:47)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)
	at scala.collection.AbstractIterator.to(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:265)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:252)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1157)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$12.apply(RDD.scala:927)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$12.apply(RDD.scala:927)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

16/03/15 19:26:45 INFO scheduler.TaskSetManager: Starting task 0.1 in stage 0.0 (TID 1, yuntu2, partition 0,PROCESS_LOCAL, 1966 bytes)

I have 3 slave nodes. 
one is on  Ubuntu 14.04.3 LTS
the 2 nodes are Ubuntu 14.10

And i see the version of  libboost are different. 

 Ubuntu 14.04.3 LTS  -----> libboost_system.so.1.54
 Ubuntu 14.10             -----> libboost_system.so.1.55

i'd like to know which version of ubuntu do you test?

**Comment by mriduljain** [comment]
Whatever version you have compiled with, make sure that the same is available on all your machines.

**Comment by dejunzhang** [comment]
@mriduljain thank you for your help. yes. i will do it.
