### ISSUE TITLE
no caffedistri in java.library.path

### ISSUE THREAD

**Issue by melody-rain** [yahoo/CaffeOnSpark#8]
WARN scheduler.TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0, melodyrain-node2): java.lang.UnsatisfiedLinkError: no caffedistri in java.library.path

Does the WARN matter? I got 

WARN server.TransportChannelHandler: Exception in connection from melodyrain-node2/192.168.0.103:33104
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)

later and the program stops.

**Comment by mriduljain** [comment]
Are you running is on osx or linux?

**Comment by melody-rain** [comment]
@mriduljain in linux with one master node and two slave nodes, in total 3 computers. I followed https://github.com/yahoo/CaffeOnSpark/wiki/GetStarted_local  to set up the clusters.

mnist works on the master node without the two slaves, but fails when the two slaves compute mnist together with the master.

Should I set caffedistri's path in the slave nodes?

**Comment by mriduljain** [comment]
No. Could you check the spark logs please? Also check the spark webui

**Comment by melody-rain** [comment]
@mriduljain 
Here is the log from webui. It says 
-----
16/02/26 18:10:58 ERROR Executor: Exception in task 0.2 in stage 0.0 (TID 2)
java.lang.UnsatisfiedLinkError: no caffedistri in java.library.path
-----


 1.6.0 stderr log page for app-20160226181032-0001/1
Back to Master

Previous 0 B Bytes 0 - 10240 of 10240Next 0 B
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
16/02/26 18:10:55 INFO CoarseGrainedExecutorBackend: Registered signal handlers for [TERM, HUP, INT]
16/02/26 18:10:56 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/02/26 18:10:56 INFO SecurityManager: Changing view acls to: hadoop
16/02/26 18:10:56 INFO SecurityManager: Changing modify acls to: hadoop
16/02/26 18:10:56 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(hadoop); users with modify permissions: Set(hadoop)
16/02/26 18:10:56 INFO SecurityManager: Changing view acls to: hadoop
16/02/26 18:10:56 INFO SecurityManager: Changing modify acls to: hadoop
16/02/26 18:10:56 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(hadoop); users with modify permissions: Set(hadoop)
16/02/26 18:10:57 INFO Slf4jLogger: Slf4jLogger started
16/02/26 18:10:57 INFO Remoting: Starting remoting
16/02/26 18:10:57 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkExecutorActorSystem@192.168.0.102:40839]
16/02/26 18:10:57 INFO Utils: Successfully started service 'sparkExecutorActorSystem' on port 40839.
16/02/26 18:10:57 INFO DiskBlockManager: Created local directory at /tmp/spark-5a34fc6c-f790-4d89-8842-6d7b4bb06ebc/executor-d39291fe-44e8-440d-9140-d7a4b062558d/blockmgr-29be1193-da4b-4649-a8d0-3a6c7cf91852
16/02/26 18:10:57 INFO MemoryStore: MemoryStore started with capacity 511.1 MB
16/02/26 18:10:57 INFO CoarseGrainedExecutorBackend: Connecting to driver: spark://CoarseGrainedScheduler@192.168.0.101:53181
16/02/26 18:10:57 INFO WorkerWatcher: Connecting to worker spark://Worker@192.168.0.102:9092
16/02/26 18:10:57 INFO CoarseGrainedExecutorBackend: Successfully registered with driver
16/02/26 18:10:57 INFO Executor: Starting executor ID 1 on host node1-padl
16/02/26 18:10:57 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 51354.
16/02/26 18:10:57 INFO NettyBlockTransferService: Server created on 51354
16/02/26 18:10:57 INFO BlockManagerMaster: Trying to register BlockManager
16/02/26 18:10:57 INFO BlockManagerMaster: Registered BlockManager
16/02/26 18:10:57 INFO CoarseGrainedExecutorBackend: Got assigned task 2
16/02/26 18:10:57 INFO Executor: Running task 0.2 in stage 0.0 (TID 2)
16/02/26 18:10:57 INFO Executor: Fetching http://192.168.0.101:54400/files/lenet_memory_solver.prototxt with timestamp 1456481432208
16/02/26 18:10:57 INFO Utils: Fetching http://192.168.0.101:54400/files/lenet_memory_solver.prototxt to /tmp/spark-5a34fc6c-f790-4d89-8842-6d7b4bb06ebc/executor-d39291fe-44e8-440d-9140-d7a4b062558d/spark-a2af11e4-b4c5-4b04-b93b-1d7ef59cfc47/fetchFileTemp7685508490226946751.tmp
16/02/26 18:10:57 INFO Utils: Copying /tmp/spark-5a34fc6c-f790-4d89-8842-6d7b4bb06ebc/executor-d39291fe-44e8-440d-9140-d7a4b062558d/spark-a2af11e4-b4c5-4b04-b93b-1d7ef59cfc47/-6092186471456481432208_cache to /opt/spark/spark-1.6.0/work/app-20160226181032-0001/1/./lenet_memory_solver.prototxt
16/02/26 18:10:57 INFO Executor: Fetching http://192.168.0.101:54400/files/lenet_memory_train_test.prototxt with timestamp 1456481432216
16/02/26 18:10:57 INFO Utils: Fetching http://192.168.0.101:54400/files/lenet_memory_train_test.prototxt to /tmp/spark-5a34fc6c-f790-4d89-8842-6d7b4bb06ebc/executor-d39291fe-44e8-440d-9140-d7a4b062558d/spark-a2af11e4-b4c5-4b04-b93b-1d7ef59cfc47/fetchFileTemp6792367555862386130.tmp
16/02/26 18:10:57 INFO Utils: Copying /tmp/spark-5a34fc6c-f790-4d89-8842-6d7b4bb06ebc/executor-d39291fe-44e8-440d-9140-d7a4b062558d/spark-a2af11e4-b4c5-4b04-b93b-1d7ef59cfc47/-17611742531456481432216_cache to /opt/spark/spark-1.6.0/work/app-20160226181032-0001/1/./lenet_memory_train_test.prototxt
16/02/26 18:10:57 INFO Executor: Fetching http://192.168.0.101:54400/jars/caffe-grid-0.1-SNAPSHOT-jar-with-dependencies.jar with timestamp 1456481432107
16/02/26 18:10:57 INFO Utils: Fetching http://192.168.0.101:54400/jars/caffe-grid-0.1-SNAPSHOT-jar-with-dependencies.jar to /tmp/spark-5a34fc6c-f790-4d89-8842-6d7b4bb06ebc/executor-d39291fe-44e8-440d-9140-d7a4b062558d/spark-a2af11e4-b4c5-4b04-b93b-1d7ef59cfc47/fetchFileTemp7018139199715769104.tmp
16/02/26 18:10:57 INFO Utils: Copying /tmp/spark-5a34fc6c-f790-4d89-8842-6d7b4bb06ebc/executor-d39291fe-44e8-440d-9140-d7a4b062558d/spark-a2af11e4-b4c5-4b04-b93b-1d7ef59cfc47/15478989671456481432107_cache to /opt/spark/spark-1.6.0/work/app-20160226181032-0001/1/./caffe-grid-0.1-SNAPSHOT-jar-with-dependencies.jar
16/02/26 18:10:57 INFO Executor: Adding file:/opt/spark/spark-1.6.0/work/app-20160226181032-0001/1/./caffe-grid-0.1-SNAPSHOT-jar-with-dependencies.jar to class loader
16/02/26 18:10:58 INFO TorrentBroadcast: Started reading broadcast variable 0
16/02/26 18:10:58 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 1962.0 B, free 1962.0 B)
16/02/26 18:10:58 INFO TorrentBroadcast: Reading broadcast variable 0 took 95 ms
16/02/26 18:10:58 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 3.0 KB, free 4.9 KB)
16/02/26 18:10:58 INFO CaffeProcessor: my rank is 0
16/02/26 18:10:58 INFO LMDB: Batch size:64
16/02/26 18:10:58 ERROR Executor: Exception in task 0.2 in stage 0.0 (TID 2)
java.lang.UnsatisfiedLinkError: no caffedistri in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.yahoo.ml.jcaffe.BaseObject.<clinit>(BaseObject.java:10)
	at com.yahoo.ml.caffe.CaffeProcessor.<init>(CaffeProcessor.scala:55)
	at com.yahoo.ml.caffe.CaffeProcessor$.instance(CaffeProcessor.scala:21)
	at com.yahoo.ml.caffe.CaffeOnSpark$$anonfun$4.apply(CaffeOnSpark.scala:123)
	at com.yahoo.ml.caffe.CaffeOnSpark$$anonfun$4.apply(CaffeOnSpark.scala:121)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:103)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:47)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)
	at scala.collection.AbstractIterator.to(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:265)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:252)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1157)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$12.apply(RDD.scala:927)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$12.apply(RDD.scala:927)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
16/02/26 18:10:58 ERROR SparkUncaughtExceptionHandler: Uncaught exception in thread Thread[Executor task launch worker-0,5,main]
java.lang.UnsatisfiedLinkError: no caffedistri in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.yahoo.ml.jcaffe.BaseObject.<clinit>(BaseObject.java:10)
	at com.yahoo.ml.caffe.CaffeProcessor.<init>(CaffeProcessor.scala:55)
	at com.yahoo.ml.caffe.CaffeProcessor$.instance(CaffeProcessor.scala:21)
	at com.yahoo.ml.caffe.CaffeOnSpark$$anonfun$4.apply(CaffeOnSpark.scala:123)
	at com.yahoo.ml.caffe.CaffeOnSpark$$anonfun$4.apply(CaffeOnSpark.scala:121)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:103)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:47)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)
	at scala.collection.AbstractIterator.to(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:265)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:252)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1157)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$12.apply(RDD.scala:927)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$12.apply(RDD.scala:927)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
16/02/26 18:10:58 INFO DiskBlockManager: Shutdown hook called
16/02/26 18:10:58 INFO ShutdownHookManager: Shutdown hook called
16/02/26 18:10:58 INFO ShutdownHookManager: Deleting directory /tmp/spark-5a34fc6c-f790-4d89-8842-6d7b4bb06ebc/executor-d39291fe-44e8-440d-9140-d7a4b062558d/spark-a2af11e4-b4c5-4b04-b93b-1d7ef59cfc47

**Comment by anfeng** [comment]
Please check your LD_LIBRARY_PATH settings. It should refer to caffe-public/distribute/lib and caffe-distri/distribute/lib (See step 5). In Step 8, you need to make sure that spark.executorEnv.LD_LIBRARY_PATH is set correctly.

If you are running slaves on separated nodes, please make sure that all of them have CaffeOnSpark installed. Your life will be simpler if you use Spark/YARN

**Comment by melody-rain** [comment]
@anfeng Please close this issue. I've successfully run mnist with YARN. Thanks a lot.

**Comment by anfeng** [comment]
@melody-rain Good news.
