### ISSUE TITLE
an error on Mesos

### ISSUE THREAD

**Issue by jsongcse** [yahoo/CaffeOnSpark#86]
Good afternoon.

Thank you for CaffeOnSpark. May I ask a question?

I tried to run the MNIST example on CaffeOnSpark. In the local mode it worked fine. But in the Mesos cluster mode, there was an error. Would you help me? I attached the Spark log below.

First, my command was:
```
/opt/spark-1.6.0-bin-hadoop2.6/bin/spark-submit \
    --files ${CAFFE_ON_SPARK}/data/lenet_memory_solver.prototxt.mesos,${CAFFE_ON_SPARK}/data/lenet_memory_train_test.prototxt.mesos \
    --conf spark.driver.extraLibraryPath="${LD_LIBRARY_PATH}" \
    --conf spark.executorEnv.LD_LIBRARY_PATH="${LD_LIBRARY_PATH}" \
    --class com.yahoo.ml.caffe.CaffeOnSpark  \
    ${CAFFE_ON_SPARK}/caffe-grid/target/caffe-grid-0.1-SNAPSHOT-jar-with-dependencies.jar \
        -train \
        -features accuracy,loss -label label \
        -conf ${CAFFE_ON_SPARK}/data/lenet_memory_solver.prototxt.mesos \
        -devices ${DEVICES} \
        -connection ethernet \
        -model hdfs:///mnist.model \
        -output hdfs:///mnist_features_result
```
I modified `${CAFFE_ON_SPARK}/data/lenet_memory_solver.prototxt.mesos` so that it would look for `${CAFFE_ON_SPARK}/data/lenet_memory_train_test.prototxt.mesos` in each worker computer. I copied `lenet_memory_train_test.prototxt.mesos` to each worker computer at the same path.

Then there was an error:
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/spark-1.6.0-bin-hadoop2.6/lib/spark-assembly-1.6.0-hadoop2.6.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/spark-1.6.0-bin-hadoop2.6/lib/spark-examples-1.6.0-hadoop2.6.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
16/06/16 15:46:49 INFO SparkContext: Running Spark version 1.6.0
16/06/16 15:46:49 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/06/16 15:46:49 INFO SecurityManager: Changing view acls to: hadoop
16/06/16 15:46:49 INFO SecurityManager: Changing modify acls to: hadoop
16/06/16 15:46:49 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(hadoop); users with modify permissions: Set(hadoop)
16/06/16 15:46:49 INFO Utils: Successfully started service 'sparkDriver' on port 33611.
16/06/16 15:46:49 INFO Slf4jLogger: Slf4jLogger started
16/06/16 15:46:49 INFO Remoting: Starting remoting
16/06/16 15:46:50 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkDriverActorSystem@192.168.0.2:53685]
16/06/16 15:46:50 INFO Utils: Successfully started service 'sparkDriverActorSystem' on port 53685.
16/06/16 15:46:50 INFO SparkEnv: Registering MapOutputTracker
16/06/16 15:46:50 INFO SparkEnv: Registering BlockManagerMaster
16/06/16 15:46:50 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-7c2b7f3a-9a1a-4624-ace3-51bcdfa38d2e
16/06/16 15:46:50 INFO MemoryStore: MemoryStore started with capacity 511.1 MB
16/06/16 15:46:50 INFO SparkEnv: Registering OutputCommitCoordinator
16/06/16 15:46:50 INFO Utils: Successfully started service 'SparkUI' on port 4040.
16/06/16 15:46:50 INFO SparkUI: Started SparkUI at http://192.168.0.2:4040
16/06/16 15:46:50 INFO HttpFileServer: HTTP File server directory is /tmp/spark-e28ec4b7-cffb-474d-a920-e65632853235/httpd-a725ec82-a8f4-4e18-8577-b7dfcbb93a46
16/06/16 15:46:50 INFO HttpServer: Starting HTTP Server
16/06/16 15:46:50 INFO Utils: Successfully started service 'HTTP file server' on port 46356.
16/06/16 15:46:50 INFO SparkContext: Added JAR file:/home/hadoop/jaewoo.song/CaffeOnSpark/caffe-grid/target/caffe-grid-0.1-SNAPSHOT-jar-with-dependencies.jar at http://192.168.0.2:46356/jars/caffe-grid-0.1-SNAPSHOT-jar-with-dependencies.jar with timestamp 1466063210288
16/06/16 15:46:50 INFO Utils: Copying /home/hadoop/jaewoo.song/CaffeOnSpark/data/lenet_memory_solver.prototxt.mesos to /tmp/spark-e28ec4b7-cffb-474d-a920-e65632853235/userFiles-443ed678-92ee-404d-bf06-5fddafd23d08/lenet_memory_solver.prototxt.mesos
16/06/16 15:46:50 INFO SparkContext: Added file file:/home/hadoop/jaewoo.song/CaffeOnSpark/data/lenet_memory_solver.prototxt.mesos at http://192.168.0.2:46356/files/lenet_memory_solver.prototxt.mesos with timestamp 1466063210375
16/06/16 15:46:50 INFO Utils: Copying /home/hadoop/jaewoo.song/CaffeOnSpark/data/lenet_memory_train_test.prototxt.mesos to /tmp/spark-e28ec4b7-cffb-474d-a920-e65632853235/userFiles-443ed678-92ee-404d-bf06-5fddafd23d08/lenet_memory_train_test.prototxt.mesos
16/06/16 15:46:50 INFO SparkContext: Added file file:/home/hadoop/jaewoo.song/CaffeOnSpark/data/lenet_memory_train_test.prototxt.mesos at http://192.168.0.2:46356/files/lenet_memory_train_test.prototxt.mesos with timestamp 1466063210383
I0616 15:46:50.541450  3442 sched.cpp:222] Version: 0.28.0
2016-06-16 15:46:50,543:3351(0x7fc3593e4700):ZOO_INFO@log_env@712: Client environment:zookeeper.version=zookeeper C client 3.4.5
2016-06-16 15:46:50,543:3351(0x7fc3593e4700):ZOO_INFO@log_env@716: Client environment:host.name=hkcloud-node1
2016-06-16 15:46:50,543:3351(0x7fc3593e4700):ZOO_INFO@log_env@723: Client environment:os.name=Linux
2016-06-16 15:46:50,543:3351(0x7fc3593e4700):ZOO_INFO@log_env@724: Client environment:os.arch=3.10.0-327.10.1.el7.x86_64
2016-06-16 15:46:50,543:3351(0x7fc3593e4700):ZOO_INFO@log_env@725: Client environment:os.version=#1 SMP Tue Feb 16 17:03:50 UTC 2016
2016-06-16 15:46:50,543:3351(0x7fc3593e4700):ZOO_INFO@log_env@733: Client environment:user.name=hadoop
2016-06-16 15:46:50,544:3351(0x7fc3593e4700):ZOO_INFO@log_env@741: Client environment:user.home=/home/hadoop
2016-06-16 15:46:50,544:3351(0x7fc3593e4700):ZOO_INFO@log_env@753: Client environment:user.dir=/home/hadoop/jaewoo.song/CaffeOnSpark
2016-06-16 15:46:50,544:3351(0x7fc3593e4700):ZOO_INFO@zookeeper_init@786: Initiating client connection, host=hkcloud-m:2181,hkcloud-node1:2181,hkcloud-node2:2181 sessionTimeout=10000 watcher=0x7fc365896280 sessionId=0 sessionPasswd=<null> context=0x7fc398004680 flags=0
2016-06-16 15:46:50,547:3351(0x7fc3572df700):ZOO_INFO@check_events@1703: initiated connection to server [192.168.0.2:2181]
2016-06-16 15:46:50,556:3351(0x7fc3572df700):ZOO_INFO@check_events@1750: session establishment complete on server [192.168.0.2:2181], sessionId=0x25515b774600033, negotiated timeout=10000
I0616 15:46:50.556560  3437 group.cpp:349] Group process (group(1)@192.168.0.2:48907) connected to ZooKeeper
I0616 15:46:50.556592  3437 group.cpp:831] Syncing group operations: queue size (joins, cancels, datas) = (0, 0, 0)
I0616 15:46:50.556603  3437 group.cpp:427] Trying to create path '/mesos' in ZooKeeper
I0616 15:46:50.557202  3437 detector.cpp:152] Detected a new leader: (id='86')
I0616 15:46:50.557274  3437 group.cpp:700] Trying to get '/mesos/json.info_0000000086' in ZooKeeper
I0616 15:46:50.557571  3437 detector.cpp:479] A new leading master (UPID=master@192.168.0.3:5050) is detected
I0616 15:46:50.557610  3437 sched.cpp:326] New master detected at master@192.168.0.3:5050
I0616 15:46:50.557930  3437 sched.cpp:336] No credentials provided. Attempting to register without authentication
I0616 15:46:50.564281  3437 sched.cpp:703] Framework registered with a179a27d-cd33-4e1d-a996-5afec0bc1c4b-0035
16/06/16 15:46:50 INFO CoarseMesosSchedulerBackend: Registered as framework ID a179a27d-cd33-4e1d-a996-5afec0bc1c4b-0035
16/06/16 15:46:50 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 35384.
16/06/16 15:46:50 INFO NettyBlockTransferService: Server created on 35384
16/06/16 15:46:50 INFO BlockManagerMaster: Trying to register BlockManager
16/06/16 15:46:50 INFO BlockManagerMasterEndpoint: Registering block manager 192.168.0.2:35384 with 511.1 MB RAM, BlockManagerId(driver, 192.168.0.2, 35384)
16/06/16 15:46:50 INFO BlockManagerMaster: Registered BlockManager
16/06/16 15:46:50 INFO CoarseMesosSchedulerBackend: Mesos task 0 is now TASK_RUNNING
16/06/16 15:46:50 INFO CoarseMesosSchedulerBackend: Mesos task 1 is now TASK_RUNNING
16/06/16 15:46:50 INFO CoarseMesosSchedulerBackend: Mesos task 2 is now TASK_RUNNING
16/06/16 15:46:52 INFO CoarseMesosSchedulerBackend: Registered executor NettyRpcEndpointRef(null) (hkcloud-node2:49157) with ID f73f53d0-4f46-4691-ad01-5fed545d76e5-S0
16/06/16 15:46:52 INFO CoarseMesosSchedulerBackend: Registered executor NettyRpcEndpointRef(null) (hkcloud-node1:60208) with ID 753a7274-173a-41bf-b800-0345adc29be0-S0
16/06/16 15:46:52 INFO BlockManagerMasterEndpoint: Registering block manager hkcloud-node2:52796 with 511.1 MB RAM, BlockManagerId(f73f53d0-4f46-4691-ad01-5fed545d76e5-S0, hkcloud-node2, 52796)
16/06/16 15:46:52 INFO BlockManagerMasterEndpoint: Registering block manager hkcloud-node1:55612 with 511.1 MB RAM, BlockManagerId(753a7274-173a-41bf-b800-0345adc29be0-S0, hkcloud-node1, 55612)
16/06/16 15:46:52 INFO CoarseMesosSchedulerBackend: Registered executor NettyRpcEndpointRef(null) (hkcloud-m:60051) with ID 114d8677-dbe9-4b2a-bf79-dc4a34d2cede-S3
16/06/16 15:46:52 INFO BlockManagerMasterEndpoint: Registering block manager hkcloud-m:41380 with 511.1 MB RAM, BlockManagerId(114d8677-dbe9-4b2a-bf79-dc4a34d2cede-S3, hkcloud-m, 41380)
16/06/16 15:47:20 INFO CoarseMesosSchedulerBackend: SchedulerBackend is ready for scheduling beginning after waiting maxRegisteredResourcesWaitingTime: 30000(ms)
16/06/16 15:47:21 INFO DataSource$: Source data layer:0
16/06/16 15:47:21 INFO LMDB: Batch size:1
16/06/16 15:47:21 INFO SparkContext: Starting job: collect at CaffeOnSpark.scala:127
16/06/16 15:47:21 INFO DAGScheduler: Got job 0 (collect at CaffeOnSpark.scala:127) with 1 output partitions
16/06/16 15:47:21 INFO DAGScheduler: Final stage: ResultStage 0 (collect at CaffeOnSpark.scala:127)
16/06/16 15:47:21 INFO DAGScheduler: Parents of final stage: List()
16/06/16 15:47:21 INFO DAGScheduler: Missing parents: List()
16/06/16 15:47:21 INFO DAGScheduler: Submitting ResultStage 0 (MapPartitionsRDD[3] at map at CaffeOnSpark.scala:116), which has no missing parents
16/06/16 15:47:21 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 3.3 KB, free 3.3 KB)
16/06/16 15:47:21 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 2.1 KB, free 5.3 KB)
16/06/16 15:47:21 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on 192.168.0.2:35384 (size: 2.1 KB, free: 511.1 MB)
16/06/16 15:47:21 INFO SparkContext: Created broadcast 0 from broadcast at DAGScheduler.scala:1006
16/06/16 15:47:21 INFO DAGScheduler: Submitting 1 missing tasks from ResultStage 0 (MapPartitionsRDD[3] at map at CaffeOnSpark.scala:116)
16/06/16 15:47:21 INFO TaskSchedulerImpl: Adding task set 0.0 with 1 tasks
16/06/16 15:47:21 INFO TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0, hkcloud-node1, partition 0,PROCESS_LOCAL, 2209 bytes)
16/06/16 15:47:22 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on hkcloud-node1:55612 (size: 2.1 KB, free: 511.1 MB)
16/06/16 15:47:23 ERROR TaskSchedulerImpl: Lost executor 753a7274-173a-41bf-b800-0345adc29be0-S0 on hkcloud-node1: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
16/06/16 15:47:23 WARN TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0, hkcloud-node1): ExecutorLostFailure (executor 753a7274-173a-41bf-b800-0345adc29be0-S0 exited caused by one of the running tasks) Reason: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
16/06/16 15:47:23 INFO DAGScheduler: Executor lost: 753a7274-173a-41bf-b800-0345adc29be0-S0 (epoch 0)
16/06/16 15:47:23 INFO BlockManagerMasterEndpoint: Trying to remove executor 753a7274-173a-41bf-b800-0345adc29be0-S0 from BlockManagerMaster.
16/06/16 15:47:23 INFO BlockManagerMasterEndpoint: Removing block manager BlockManagerId(753a7274-173a-41bf-b800-0345adc29be0-S0, hkcloud-node1, 55612)
16/06/16 15:47:23 INFO TaskSetManager: Starting task 0.1 in stage 0.0 (TID 1, hkcloud-node2, partition 0,PROCESS_LOCAL, 2209 bytes)
16/06/16 15:47:23 INFO BlockManagerMaster: Removed 753a7274-173a-41bf-b800-0345adc29be0-S0 successfully in removeExecutor
16/06/16 15:47:23 INFO CoarseMesosSchedulerBackend: Mesos task 2 is now TASK_FAILED
16/06/16 15:47:23 INFO CoarseMesosSchedulerBackend: Mesos task 3 is now TASK_RUNNING
16/06/16 15:47:24 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on hkcloud-node2:52796 (size: 2.1 KB, free: 511.1 MB)
16/06/16 15:47:24 ERROR TaskSchedulerImpl: Lost executor f73f53d0-4f46-4691-ad01-5fed545d76e5-S0 on hkcloud-node2: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
16/06/16 15:47:24 WARN TaskSetManager: Lost task 0.1 in stage 0.0 (TID 1, hkcloud-node2): ExecutorLostFailure (executor f73f53d0-4f46-4691-ad01-5fed545d76e5-S0 exited caused by one of the running tasks) Reason: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
16/06/16 15:47:24 INFO DAGScheduler: Executor lost: f73f53d0-4f46-4691-ad01-5fed545d76e5-S0 (epoch 1)
16/06/16 15:47:24 INFO BlockManagerMasterEndpoint: Trying to remove executor f73f53d0-4f46-4691-ad01-5fed545d76e5-S0 from BlockManagerMaster.
16/06/16 15:47:24 INFO BlockManagerMasterEndpoint: Removing block manager BlockManagerId(f73f53d0-4f46-4691-ad01-5fed545d76e5-S0, hkcloud-node2, 52796)
16/06/16 15:47:24 INFO BlockManagerMaster: Removed f73f53d0-4f46-4691-ad01-5fed545d76e5-S0 successfully in removeExecutor
16/06/16 15:47:24 INFO TaskSetManager: Starting task 0.2 in stage 0.0 (TID 2, hkcloud-m, partition 0,PROCESS_LOCAL, 2209 bytes)
16/06/16 15:47:24 INFO CoarseMesosSchedulerBackend: Mesos task 0 is now TASK_FAILED
16/06/16 15:47:24 INFO CoarseMesosSchedulerBackend: Mesos task 4 is now TASK_RUNNING
16/06/16 15:47:25 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on hkcloud-m:41380 (size: 2.1 KB, free: 511.1 MB)
16/06/16 15:47:25 ERROR TaskSchedulerImpl: Lost executor 114d8677-dbe9-4b2a-bf79-dc4a34d2cede-S3 on hkcloud-m: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
16/06/16 15:47:25 WARN TaskSetManager: Lost task 0.2 in stage 0.0 (TID 2, hkcloud-m): ExecutorLostFailure (executor 114d8677-dbe9-4b2a-bf79-dc4a34d2cede-S3 exited caused by one of the running tasks) Reason: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
16/06/16 15:47:25 INFO DAGScheduler: Executor lost: 114d8677-dbe9-4b2a-bf79-dc4a34d2cede-S3 (epoch 2)
16/06/16 15:47:25 INFO BlockManagerMasterEndpoint: Trying to remove executor 114d8677-dbe9-4b2a-bf79-dc4a34d2cede-S3 from BlockManagerMaster.
16/06/16 15:47:25 INFO BlockManagerMasterEndpoint: Removing block manager BlockManagerId(114d8677-dbe9-4b2a-bf79-dc4a34d2cede-S3, hkcloud-m, 41380)
16/06/16 15:47:25 INFO BlockManagerMaster: Removed 114d8677-dbe9-4b2a-bf79-dc4a34d2cede-S3 successfully in removeExecutor
16/06/16 15:47:25 INFO CoarseMesosSchedulerBackend: Registered executor NettyRpcEndpointRef(null) (hkcloud-node1:60216) with ID 753a7274-173a-41bf-b800-0345adc29be0-S0
16/06/16 15:47:25 INFO DAGScheduler: Host added was in lost list earlier: hkcloud-node1
16/06/16 15:47:25 INFO TaskSetManager: Starting task 0.3 in stage 0.0 (TID 3, hkcloud-node1, partition 0,PROCESS_LOCAL, 2209 bytes)
16/06/16 15:47:25 INFO CoarseMesosSchedulerBackend: Mesos task 1 is now TASK_FAILED
16/06/16 15:47:25 INFO BlockManagerMasterEndpoint: Registering block manager hkcloud-node1:56506 with 511.1 MB RAM, BlockManagerId(753a7274-173a-41bf-b800-0345adc29be0-S0, hkcloud-node1, 56506)
16/06/16 15:47:25 INFO CoarseMesosSchedulerBackend: Mesos task 5 is now TASK_RUNNING
16/06/16 15:47:26 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on hkcloud-node1:56506 (size: 2.1 KB, free: 511.1 MB)
16/06/16 15:47:26 INFO CoarseMesosSchedulerBackend: Registered executor NettyRpcEndpointRef(null) (hkcloud-node2:49171) with ID f73f53d0-4f46-4691-ad01-5fed545d76e5-S0
16/06/16 15:47:26 INFO DAGScheduler: Host added was in lost list earlier: hkcloud-node2
16/06/16 15:47:26 INFO BlockManagerMasterEndpoint: Registering block manager hkcloud-node2:36823 with 511.1 MB RAM, BlockManagerId(f73f53d0-4f46-4691-ad01-5fed545d76e5-S0, hkcloud-node2, 36823)
16/06/16 15:47:26 ERROR TaskSchedulerImpl: Lost executor 753a7274-173a-41bf-b800-0345adc29be0-S0 on hkcloud-node1: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
16/06/16 15:47:26 WARN TaskSetManager: Lost task 0.3 in stage 0.0 (TID 3, hkcloud-node1): ExecutorLostFailure (executor 753a7274-173a-41bf-b800-0345adc29be0-S0 exited caused by one of the running tasks) Reason: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
16/06/16 15:47:26 ERROR TaskSetManager: Task 0 in stage 0.0 failed 4 times; aborting job
16/06/16 15:47:26 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool 
16/06/16 15:47:26 INFO TaskSchedulerImpl: Cancelling stage 0
16/06/16 15:47:26 INFO DAGScheduler: ResultStage 0 (collect at CaffeOnSpark.scala:127) failed in 4.689 s
16/06/16 15:47:26 INFO DAGScheduler: Executor lost: 753a7274-173a-41bf-b800-0345adc29be0-S0 (epoch 3)
16/06/16 15:47:26 INFO DAGScheduler: Job 0 failed: collect at CaffeOnSpark.scala:127, took 4.909061 s
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3, hkcloud-node1): ExecutorLostFailure (executor 753a7274-173a-41bf-b800-0345adc29be0-S0 exited caused by one of the running tasks) Reason: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1431)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1419)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1418)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1418)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
	at scala.Option.foreach(Option.scala:236)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:799)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1640)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1599)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1588)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:620)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1832)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1845)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1858)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1929)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:927)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:926)
	at com.yahoo.ml.caffe.CaffeOnSpark.train(CaffeOnSpark.scala:127)
	at com.yahoo.ml.caffe.CaffeOnSpark$.main(CaffeOnSpark.scala:40)
	at com.yahoo.ml.caffe.CaffeOnSpark.main(CaffeOnSpark.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
16/06/16 15:47:26 INFO SparkContext: Invoking stop() from shutdown hook
16/06/16 15:47:26 INFO BlockManagerMasterEndpoint: Trying to remove executor 753a7274-173a-41bf-b800-0345adc29be0-S0 from BlockManagerMaster.
16/06/16 15:47:26 INFO BlockManagerMasterEndpoint: Removing block manager BlockManagerId(753a7274-173a-41bf-b800-0345adc29be0-S0, hkcloud-node1, 56506)
16/06/16 15:47:26 INFO BlockManagerMaster: Removed 753a7274-173a-41bf-b800-0345adc29be0-S0 successfully in removeExecutor
16/06/16 15:47:26 INFO SparkUI: Stopped Spark web UI at http://192.168.0.2:4040
16/06/16 15:47:26 INFO CoarseMesosSchedulerBackend: Mesos task 3 is now TASK_FAILED
16/06/16 15:47:26 INFO CoarseMesosSchedulerBackend: Blacklisting Mesos slave 753a7274-173a-41bf-b800-0345adc29be0-S0 due to too many failures; is Spark installed on it?
16/06/16 15:47:26 INFO CoarseMesosSchedulerBackend: Shutting down all executors
16/06/16 15:47:26 INFO CoarseMesosSchedulerBackend: Asking each executor to shut down
I0616 15:47:26.619835  3641 sched.cpp:1903] Asked to stop the driver
I0616 15:47:26.622957  3433 sched.cpp:1143] Stopping framework 'a179a27d-cd33-4e1d-a996-5afec0bc1c4b-0035'
16/06/16 15:47:26 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
16/06/16 15:47:26 INFO CoarseMesosSchedulerBackend: driver.run() returned with code DRIVER_STOPPED
16/06/16 15:47:26 INFO MemoryStore: MemoryStore cleared
16/06/16 15:47:26 INFO BlockManager: BlockManager stopped
16/06/16 15:47:26 INFO BlockManagerMaster: BlockManagerMaster stopped
16/06/16 15:47:26 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
16/06/16 15:47:26 INFO RemoteActorRefProvider$RemotingTerminator: Shutting down remote daemon.
16/06/16 15:47:26 INFO RemoteActorRefProvider$RemotingTerminator: Remote daemon shut down; proceeding with flushing remote transports.
16/06/16 15:47:26 INFO SparkContext: Successfully stopped SparkContext
16/06/16 15:47:26 INFO ShutdownHookManager: Shutdown hook called
16/06/16 15:47:26 INFO ShutdownHookManager: Deleting directory /tmp/spark-e28ec4b7-cffb-474d-a920-e65632853235/httpd-a725ec82-a8f4-4e18-8577-b7dfcbb93a46
16/06/16 15:47:26 INFO ShutdownHookManager: Deleting directory /tmp/spark-e28ec4b7-cffb-474d-a920-e65632853235
```
I had changed the batch size to 1 to avoid any not-enough-memory problem. Meanwhile, a default example Spark program in `spark-directory/example/src/main/python/pi.py` ran fine in the setting. Also, the CaffeOnSpark MNIST example ran okay in a local mode.

Thank you for your time and concern.

Regards,
Jaewoo

**Comment by anfeng** [comment]
Jaewoo:

I am not familiar with Spark on Mesos.

Your log indicates that one executor failed.

   -

   16/06/16 15:47:23 WARN TaskSetManager: Lost task 0.0 in stage 0.0
(TID 0, hkcloud-node1): ExecutorLostFailure (executor
753a7274-173a-41bf-b800-0345adc29be0-S0 exited caused by one of the
running tasks) Reason: Remote RPC client disassociated. Likely due to
containers exceeding thresholds, or network issues. Check driver logs
for WARN messages.


Please check out your executor log.

How many executors do you use? What's the value for ${DEVICES}?


Andy

Andy

**Comment by jsongcse** [comment]
Dear Andy,

Good afternoon. Thank you for your reply.

Below is what I found in the log directory of spark master node. It seems there is not much information. (I tried to find logs of spark worker nodes but I couldn't.)
```
{"Event":"SparkListenerLogStart","Spark Version":"1.6.0"}
{"Event":"SparkListenerBlockManagerAdded","Block Manager ID":{"Executor ID":"driver","Host":"10.70.22.37","Port":60428},"Maximum Memory":1307836416,"Timestamp":1466481232878}
```

Three computers are used for Apache Spark, and the cluster manager is Apache Mesos. I chose 2 for `${DEVICES}`.

Thank you for your help.

Regards,
Jaewoo

**Comment by jsongcse** [comment]
It was a problem about `-clusterSize` and `-devices` options. Apache Mesos also needs `-clusterSize` as same as YARN. Thank you for your help and encourage.

**Comment by mriduljain** [comment]
@jsongcse Please close this if it works. Would be great if you could send the doc for mesos setup (like the way we have a doc for yarn setup: https://github.com/yahoo/CaffeOnSpark/wiki/GetStarted_yarn)

**Comment by jsongcse** [comment]
Thank you for your help.
